### ISSUE TITLE
Windows 7 Taskbar 

### ISSUE THREAD

**Issue by 2Epik4u** [ImSwordQueen/Win10to7Issues#10]
**Describe the bug**
> A clear and concise description of what the bug is:

When booting up windows, the taskbar appears to be black after installing.

**To Reproduce**
> Steps to reproduce the behavior:
get a windows 10 iso
update it 
get the latest transformation and install it

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![S49g45ESyo](https://github.com/ImSwordQueen/Win10to7Issues/assets/28193089/ae13202f-ce4f-443c-90e4-81b6d8163ca7)
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/28193089/965fccef-9db8-411b-be12-5c9d52eb4d50)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 10 LTSC 2021 21H2 19044.4291]
 > Transformation Pack Version : [e.g. 3.5]
Windows 10 Pro Version 22H2 Build 19045.4529
Transformation Pack Version 3.5

**Additional context**
Applying another theme seems to have fixed the issue but it will happen again if you reboot or sign off

**Comment by ImSwordQueen** [comment]
The taskbar being black is a bug with DWMBlurGlass. restarting explorer or disabling "Override AccentBlur effect" in DWMBlurGlass would fix the issue. (The second option would disable the glass streaks on the taskbar as well)

You can find the DWMBlurGlass configurator in %Systemroot%\DWMBlurGlass
