### ISSUE TITLE
Window Titlebars irregularly big

### ISSUE THREAD

**Issue by ExileSense** [ImSwordQueen/Win10to7Issues#100]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 22H2, Freshly Installed and updated.

### What version of the Transformation Pack are you having issues with?

Latest of 11/14/2024

### Summarise the issue

The titlebars for the minimize buttons are... huge!

### Screenshots

![image](https://github.com/user-attachments/assets/57270064-b3b9-4642-8a93-23e36577b535)

### How do you reproduce the bug/inaccuracy?

1. Download the program (Latest as of 11/14/2024)
2. Run the program
3. Let the program Install (All options ticked)
4. Once installed and logged in, all title bars are the same!
5. Restarting doesnt work, Same issue

### Expected behaviour

the titlebars be the normal size... for Windows 7

**Comment by ImSwordQueen** [comment]
AWM isn't running. check if injector.exe is running in task manager.

**Comment by ExileSense** [comment]
> AWM isn't running. check if injector.exe is running in task manager.

It isnt, do i start "injector.exe" from the awm folder in C:?

**Comment by ExileSense** [comment]
> > AWM isn't running. check if injector.exe is running in task manager.
> 
> It isnt, do i start "injector.exe" from the awm folder in C:?

Update:
I tried it, and nothing happened except a cmd window opened then closed almost instantly, i also tried relogging, etc, also, the action center in the taskbar, is that gonna be a toggleable feature in future versions?

**Comment by ImSwordQueen** [comment]
I think vcredist 2022 didn't get installed. can you try installing vcredist manually and see if it works?

**Comment by victorlagarto** [comment]
installing vcredist got it to work after a reboot. thank you sm! u did a amazing job with this transformation pack

**Comment by ImSwordQueen** [comment]
> installing vcredist got it to work after a reboot. thank you sm! u did a amazing job with this transformation pack

Okay thank you for confirming the issue. I will push an update that fixes vcredist installation for new users

**Comment by ImSwordQueen** [comment]
Pushed an update that fixed the issue. If you don't wanna reinstall the pack you can just install vcredist 2022 from microsoft https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
