### ISSUE TITLE
Laptop issues

### ISSUE THREAD

**Issue by Portal2Ben** [ImSwordQueen/Win10to7Issues#101]
### Before reporting your issue

- [ ] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [ ] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Enterprise

### What version of the Transformation Pack are you having issues with?

3.5.4

### Summarise the issue

I have installed 10to7 on my laptop however whenever I unplug my laptop charger, openglass stops working and my taskbar goes red. Upon plugging the charger back in it returns to normal

In Task Scheduler I have disabled both "Start the task only if the computer is on AC power" and "Stop if the computer switches to battery power". I have only done this on "Aero_Window_Manager" and "000Openglass Host"

Any ideas?

### Screenshots

![before](https://github.com/user-attachments/assets/e882b877-2aa4-4e2f-8179-4c3ae2625558)
![after](https://github.com/user-attachments/assets/e30dfa46-576d-43cc-a791-a0a6b0a7b0fa)

### How do you reproduce the bug/inaccuracy?

1. start windows with charger plugged in
2. unplug charger

### Expected behaviour

When i unplug the charger nothing should change

**Comment by Portal2Ben** [comment]
Just solved it!

Always when you ask for help you solve it yourself anyways haha
If anyone else runs into this you also need to disable "Start the task only if the computer is on AC power" on the "Sidebarexecute" task as well and that at least solved it for me!

**Comment by Portal2Ben** [comment]
Correction it was not SidebarExecute, it is battery saver mode. Whenever my laptop enters battery saver mode, the taskbar goes red and aero blur is disabled. 

Any ideas on this one?

**Comment by ImSwordQueen** [comment]
add "DisableGlassOnBattery" 0 to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm

**Comment by Portal2Ben** [comment]
Thanks!
