### ISSUE TITLE
Built in wallpapers and aero reflection are blurry

### ISSUE THREAD

**Issue by AryaTwirl** [ImSwordQueen/Win10to7Issues#103]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 LTSC 21H2 latest update

### What version of the Transformation Pack are you having issues with?

3.5.4.2

### Summarise the issue

In the latest version, I noticed that all wallpapers and aero peek reflection effect are quite blurry, like compressed.
Any suggestions for that?

Thank you.

### How do you reproduce the bug/inaccuracy?

1. apply wallpaper or theme, or use aeropeek
2. notice bluriness

### Expected behaviour

It's not supposed to be blurry

**Comment by ImSwordQueen** [comment]
I believe this is an issue with how Windows 10 handles wallpapers. For some reason they changed how JPG images are set and instead of doing what Windows 7 it makes them worse
