### ISSUE TITLE
Can't install the pack because of a back up error.

### ISSUE THREAD

**Issue by Zer0PXL** [ImSwordQueen/Win10to7Issues#104]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 IoT Enterprise LTSC 21H2 19044.5131

### What version of the Transformation Pack are you having issues with?

3.5.4.3

### Summarise the issue

While installing the transformation pack, during step 3, I suddenly got an error telling me that it failed to backup the accessibility folder. I tried to press enter to go back to windows and it wasn't functional so I had to revert to a restore point. I have tried multiple times just in case, and it gives me the same error every time. 

I will try to delete this folder and install it again. Even though I shouldn't do that, I'm impatient.

### Screenshots

https://imgur.com/a/dxhQr3z

### How do you reproduce the bug/inaccuracy?

1. Try to install Win10to7
2. Fail

### Expected behaviour

For it to install, idk

**Comment by ImSwordQueen** [comment]
Are you using a lite/debloated/modified Windows ISO or is it a stock one?
