### ISSUE TITLE
Some features are not applied

### ISSUE THREAD

**Issue by dejo1001** [ImSwordQueen/Win10to7Issues#108]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Pro 22H2 19045.5198

### What version of the Transformation Pack are you having issues with?

3.5.4.3

### Summarise the issue

Ribbon is not applied and taskbar remains flat (win10 style).

### Screenshots

![image](https://github.com/user-attachments/assets/3f8a05e7-25e6-4de2-9b49-5c513925b1ee)
![image](https://github.com/user-attachments/assets/e2822151-3cec-4c42-8504-09d39c07dc64)
![image](https://github.com/user-attachments/assets/3874d9a4-9083-4551-9767-679992c9dc5f)
![image](https://github.com/user-attachments/assets/7507bac9-11c8-4f97-a149-05448084fbb0)

### How do you reproduce the bug/inaccuracy?

I selected the appropriate options, as shown in the screenshots.

### Expected behaviour

The options should work, as I have seen in other screenshots.

**Comment by ImSwordQueen** [comment]
Can you open any ribbon applications (eg mspaint or wordpad) and see if those work? i think the msstyle for the taskbar corrupted also somehow so if you can just reapply the pack.

**Comment by dejo1001** [comment]
I uninstalled and reinstalled the transformation pack but it still didn't work as it should.
Is there anything else I could check/try?

**Comment by ImSwordQueen** [comment]
did you have any tweaks pre-applied before?

**Comment by dejo1001** [comment]
I tried [this one](https://r8p.teknixstuff.com/) some time ago but it had several issues and I uninstalled it.

**Comment by ImSwordQueen** [comment]
Check if r8p didn't leave any windhawk mods that might cause issues with 21H2to7

**Comment by dejo1001** [comment]
What can I check? Which mods should be enabled?

**Comment by ImSwordQueen** [comment]
can you send me a screenshot of the mods you have in windhawk? just open windhawk in the tray overflow area.

**Comment by dejo1001** [comment]
![image](https://github.com/user-attachments/assets/d06a3828-0019-4bfd-819f-b77aac65b6d6)
![image](https://github.com/user-attachments/assets/ebfb412d-3961-49ca-a42e-417c5872af99)
![image](https://github.com/user-attachments/assets/c2d378b7-e171-4d39-9d80-1e41ad7b1774)
![image](https://github.com/user-attachments/assets/f0d39344-c9a4-46d3-8d5b-39ced67f619f)

The only mods I installed were _Themed Regedit ListView_ and _Transparent Screensaver Fix_, although the issue existed before I installed them.

**Comment by ImSwordQueen** [comment]
Okay it seems that R8P didn't remove the windhawk mods while it was uninstalling. Remove the duplicate mods that are stored locally and not from the store (the local ones have the cloud near them)

**Comment by dejo1001** [comment]
OK, now the ribbon is working
![image](https://github.com/user-attachments/assets/418b66e2-d3b1-4372-a705-9b419bc7d288)
but the taskbar is still "win10"
![image](https://github.com/user-attachments/assets/b08eb2b6-00e5-4ef1-a162-fc74826cfccc)
What else should I check?

**Comment by ImSwordQueen** [comment]
Is the orb using SIB or is it a different software? check if SIB isn't disabled in "Computer\HKEY_CURRENT_USER\SOFTWARE\StartIsBack" with the key "Disabled". If it isn't set to 0 then delete it and restart explorer

**Comment by dejo1001** [comment]
I'm using OpenShell Menu.
"Disabled" was 1. I set it to 0 and it worked but I want to use start menu from OpenShell. Is it possible to disable the start button from SIB?

**Comment by ImSwordQueen** [comment]
Re-enable the button in SIB and try this option in StartIsBack++ Tweaker in windhawk 
![image](https://github.com/user-attachments/assets/4bccbfe9-875d-4fb3-b399-0b26a9e10d99)

**Comment by dejo1001** [comment]
It worked, thanks!
The only annoying thing is the popup on every startup:
![image](https://github.com/user-attachments/assets/62c70e10-788b-4c89-a7b4-acb4c6d65632)
but I think I can live with that.

**Comment by ImSwordQueen** [comment]
> It worked, thanks! The only annoying thing is the popup on every startup: ![image](https://private-user-images.githubusercontent.com/179701552/391269056-62c70e10-788b-4c89-a7b4-acb4c6d65632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5OTM5MTEsIm5iZiI6MTczMjk5MzYxMSwicGF0aCI6Ii8xNzk3MDE1NTIvMzkxMjY5MDU2LTYyYzcwZTEwLTc4OGItNGM4OS1hN2I0LWFjYjRjNmQ2NTYzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxOTA2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODVjMDNjZmE3MDlkY2VkMTkxMWRhNWRkNjY3NzhmMjFiMGMyNmQ3MGVjMmMzOTRmMmVmNzkxOTNkZTUwY2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7-IynTMrhQn37FHsidfvAGG5fMsl3krGmbVRTMgkfmg) but I think I can live with that.

amrsatrio is making a replacement taskbar which is going to have a mode to skin it like 7. Right now it is in private beta but if you know where to look in the windhawk discord you might be able to set that up instead of using SIB.
