### ISSUE TITLE
Action Center icon?

### ISSUE THREAD

**Issue by dejo1001** [ImSwordQueen/Win10to7Issues#109]
### Ask your question here

How can I get rid of the action center icon (flag)? The corresponding option is already off and it applies to the icon to the right of the clock.
![image](https://github.com/user-attachments/assets/96362a88-2ef6-4ef6-9d23-43573a007933)
![image](https://github.com/user-attachments/assets/eedb8a3b-be8f-4c95-bf92-a11e794f4d30)

**Comment by ImSwordQueen** [comment]
Windows 10 doesn't have an option to disable it so a way to remove it is to do sfc /scanfile=c:\windows\system32\actioncenter.dll and sfc /scanfile=c:\windows\system32\en-us\actioncenter.dll.mui
