### ISSUE TITLE
Window opening animations are low fps/choppy

### ISSUE THREAD

**Issue by uncognic** [ImSwordQueen/Win10to7Issues#110]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 LTSC 2021 21H2 19044.5131

### What version of the Transformation Pack are you having issues with?

3.5.4.3 Hotfix

### Summarise the issue

After a fresh install of Windows, and applying this pack, it applies fine, but the window animations are very low fps. 

### How do you reproduce the bug/inaccuracy?

1. Install pack
2. Open window
3. Watch the animation

### Expected behaviour

For it to be at a normal framerate

**Comment by uncognic** [comment]
Also note, as I am submitting this issue, I have noticed that scrolling is also choppy

**Comment by uncognic** [comment]
Yeah, I am using a low end PC, Pentium 5405U and UHD 620, but with older
versions of 10to7 it would still run perfectly. I have already figured out
that it is caused by openglass 1.4, as 10to7 3.5.3 works fine

**Comment by ImSwordQueen** [comment]
in 3.5.4 i updated Openglass 1.4 and 1.4 added "EnableGeometryMerging" which makes the borders connect better than previous versions at the cost of performance. You could try disabling that by going in "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm" and deleting that registry key.

**Comment by uncognic** [comment]
Can’t test this as i’m not on this version anymore

**Comment by uncognic** [comment]
Tested, did not work. Animations still laggy

**Comment by ImSwordQueen** [comment]
That's something i can't control sadly. There might be something in 1.3/1.4 that changed that makes it lag on your end. Can't replicate it sorry.

You could always open an openglass issue so altalex gets notified of the issue i guess.
