### ISSUE TITLE
Windows stuck on fallback logon UI

### ISSUE THREAD

**Issue by skwinkles** [ImSwordQueen/Win10to7Issues#111]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 22H2

### What version of the Transformation Pack are you having issues with?

21H2-22H2 to 7

### Summarise the issue

After trying to uninstall the pack, I came back to a very glitchy version of the fallback logon ui. It won't let me sign in.

### Screenshots

![20241129_134055](https://github.com/user-attachments/assets/4c425e35-c397-48eb-a4f0-fafa7d3bd583)
![20241129_134102](https://github.com/user-attachments/assets/fc4a36d2-4bae-41b0-8e99-4514028fd5df)

### How do you reproduce the bug/inaccuracy?

1. Run the uninstaller
2. select the option to return the look and feel of Windows 10
3. Wait

### Expected behaviour

I expected it to return the Windows 10 theme.

### Additional Context

Before this, I was also having a small issue where the explorer buttons (arrows) didn't show up.

**Comment by skwinkles** [comment]
UPDATE: Extra info, I finally managed to hard shut down my laptop by draining the battery and when it booted back up it said that the DWM crashed several times (honestly assumed that) but I managed to get into safe mode and I'm pretty sure a system restore can fix it :3 Seems to be an openglass compatability issue from what I can tell

**Comment by ImSwordQueen** [comment]
Oh no, Something failed during the uninstallation so stuff didn't uninstall properly. Sadly because you didn't catch the error i can't tell what could've failed so the only thing you could do is to restore from a restore point that 21H2to7 makes

**Comment by skwinkles** [comment]
I was out of the room most of the time it was uninstalling, I might try to recreate it and actually take a picture of the error later :) Thank you though
