### ISSUE TITLE
Windhawk - Disk pie chart

### ISSUE THREAD

**Issue by dejo1001** [ImSwordQueen/Win10to7Issues#112]
### Before sending your suggestion

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version of the Windows 10to7 Transformation Pack.

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Pro 22H2 19045.5198

### What would you like to suggest for 21H2to7?

Consider adding this mod in the next release:
![image](https://github.com/user-attachments/assets/b3d67007-fcd4-49cd-8d97-f1bdef064701)

It is **much** nicer than the "new" circle.

### Additional Context

![image](https://github.com/user-attachments/assets/85ff55da-34f8-4f18-9d7c-087b8ce0cd82)

**Comment by ImSwordQueen** [comment]
Already added.
