### ISSUE TITLE
Black Screen after signing out (or logging out)

### ISSUE THREAD

**Issue by Bereallmao** [ImSwordQueen/Win10to7Issues#113]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

IOT LTSC 2021 21H2 19044.5131

### What version of the Transformation Pack are you having issues with?

3.5.4.3

### Summarise the issue

after signing out, my screen goes black. I did not tick the option to install Custom LogonUI in the installer.

### How do you reproduce the bug/inaccuracy?

1. Sign out

### Expected behaviour

I expected it to show the default Windows 10 lock screen and not a black screen.

### Additional Context

Frequency: Everytime after signing out.

I'm using a hybrid laptop with no mux switch.

**Comment by Bereallmao** [comment]
problem fixed. It was because of DWM Unextend Frames messing with the LogonUI.

**Comment by Somerandomperson01** [comment]
May I ask how you get DWM to stop messing with the LogonUI as I am having this same issue?

**Comment by Bereallmao** [comment]
> May I ask how you get DWM to stop messing with the LogonUI as I am having this same issue?

well I just disable the "DWM Unextend Frames" mod in Windhawk. Apparently it also disables LogonUI DWM thus resulting in this problem. Not sure but I think there is a setting to change that.

Sorry for the late response, wasn't paying attention to github lately.
