### ISSUE TITLE
OpenGlass could not download appropriate symbol files

### ISSUE THREAD

**Issue by dejo1001** [ImSwordQueen/Win10to7Issues#114]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Pro 22H2 19045.5198

### What version of the Transformation Pack are you having issues with?

3.5.4.3

### Summarise the issue

Every time I start the computer I get the above error and glass colors don't work.
I have copied the symbols folder from c:\awm to c:\windows\openglass but it didn't work.

### Screenshots

![openglass](https://github.com/user-attachments/assets/bcd9fd4f-253d-4ae7-b2a3-dcbb29b88bfe)

### How do you reproduce the bug/inaccuracy?

.

### Expected behaviour

.

**Comment by ImSwordQueen** [comment]
It should've worked because AWM is running. Did you restart dwm as well?

**Comment by dejo1001** [comment]
I restarted the computer. The first time it was ok but after another restart I got the error again.

**Comment by ImSwordQueen** [comment]
> I restarted the computer. The first time it was ok but after another restart I got the error again.

This sounds like a weird bug with openglass. I would try removing the symbols folder from openglass and recopy the awm one if it is still not working

**Comment by Somerandomperson01** [comment]
I remember having this same issue and somehow fixed it using this post:
https://github.com/ALTaleX531/OpenGlass/issues/26 
If you have any issues then let me know here.

**Comment by victorlagarto** [comment]
I am having exactly the same problem. Couldn't get it to work even with the post mentioned. BTW, this happened after a Windows Update (screenshot of the update below)
![image](https://github.com/user-attachments/assets/57f045d0-985f-4d0e-93fc-5a259a7ee25b)

**Comment by Somerandomperson01** [comment]
Yea Windows Update is known to break certain things including the login screen (This actually happened to me a couple days ago). I would reinstall the transformation pack, HOWEVER, it will not fix OpenGlass for you.

Here's the symbol folder that I have which is working and has that exact same update that you mentioned, just replace the one you currently have with mines:

https://drive.google.com/file/d/13JHRv3Pp442cUecRWB2ZA1G9IZTuZRdL/view?usp=sharing

**Comment by ImSwordQueen** [comment]
Made 2 scripts (based on the main symbols downloader of 21H2to7) that should download symbols or just copy them from the windhawk folder depending on the script.

[DWM Symbols fix](https://github.com/user-attachments/files/18131858/DWM.Symbols.fix.zip)

[DWM Symbols Downloader](https://github.com/user-attachments/files/18131878/DWM.Symbols.Downloader.zip)
