### ISSUE TITLE
Change lockscreen background image

### ISSUE THREAD

**Issue by lkk9898969** [ImSwordQueen/Win10to7Issues#115]
### Before sending your suggestion

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version of the Windows 10to7 Transformation Pack.

### What version of Windows 10 are you using the transformation pack on?

Windows 10 LTSC 2021 21H2 19044.5131

### What would you like to suggest for 21H2to7?

Is it able to change lockscreen background image? Because I didn't find where can change.
I tried third party software to change it (ie. displayfusion) but it didn't work.

**Comment by ImSwordQueen** [comment]
https://www.howtogeek.com/112110/how-to-set-a-custom-logon-screen-background-on-windows-7/

**Comment by lkk9898969** [comment]
> https://www.howtogeek.com/112110/how-to-set-a-custom-logon-screen-background-on-windows-7/

Very thanks!
