### ISSUE TITLE
Taskbar appearance inconsistent

### ISSUE THREAD

**Issue by dejo1001** [ImSwordQueen/Win10to7Issues#116]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Pro 22H2 19045.5131

### What version of the Transformation Pack are you having issues with?

3.5.4.3

### Summarise the issue

This is a fresh transformation, never installed any kind of transformation packs before.
Custom coloring in SIB is disabled. Perks > Segments is also disabled.

### Screenshots

![image](https://github.com/user-attachments/assets/94799870-db01-40c2-852c-de5eb6d750ca)

### How do you reproduce the bug/inaccuracy?

Fresh install

### Expected behaviour

The whole taskbar should be glass, not just parts of it.

**Comment by ImSwordQueen** [comment]
The theme hasn't been applied in startisback or openshell is applying setting on top.
