### ISSUE TITLE
ImmersiveCPL.exe being flagged as a Trojan by various anti-malware suites

### ISSUE THREAD

**Issue by AdityaKKhullar** [ImSwordQueen/Win10to7Issues#12]
So I've been facing this problem that Kaspersky has been fucking up the entire transformation all the time by deleting this file known as ImmersiveCPL.exe located in the Windows folder. It seems like this executable assists in adding the old control panel options?? (When the antimalware/antivirus deletes the file, the screen resolution option from the right-click on desktop stops working).
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/72785876/b1e88380-55d6-4fac-8b55-228b12b18e93)

What is this file exactly? Why is it being flagged as a malware?

**Comment by ImSwordQueen** [comment]
The executable redirects some hardcoded UWP settings redirects to the control panel settings. it was made by brawllux on winclassic here: https://winclassic.net/thread/1779/restoring-control-panel-pages-links
