### ISSUE TITLE
Would it be possible to change the User Screen's background?

### ISSUE THREAD

**Issue by CatalonianPunIntended** [ImSwordQueen/Win10to7Issues#120]
### Ask your question here

Hello,

So some OEMs changed the background of the screen to match the OEM itself. (by example, Acer did that) Would it be possible to do that?

THE STORY (not an excuse)
So I was thinking of this when I thought of buying new components for my grandfather's computer. His computer, to this day, still runs a pirated copy of Windows 7. As Windows 7 is so slow nowadays, I am thinking of buying him new components someday and using Win10to7, because I can't imagine his computer in jet black corporate style, and also because what he loves most to do with his computer is play Solitaire, so having to use the micropayment-filled version is just nerve-wracking.

**Comment by ImSwordQueen** [comment]
https://www.howtogeek.com/112110/how-to-set-a-custom-logon-screen-background-on-windows-7/


Also, Please make sure that you can control the machine each month. Monthly updates have been terrible for mods by unpatching files that are modified by the TP
