### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Zanut123** [ImSwordQueen/Win10to7Issues#121]
### Before reporting your issue

- [x] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Home 22H2 19045.5247

### What version of the Transformation Pack are you having issues with?

3.5.4

### Summarise the issue

when i install this in my pc a black screen appears with cursor after login

### How do you reproduce the bug/inaccuracy?

simply after all stages of instalation

### Expected behaviour

windows transformed correctly

**Comment by ImSwordQueen** [comment]
Did you have internet on at all times during installation? You can revert before the installation thru a restore point that the transformation pack makes

**Comment by Zanut123** [comment]
I think so

**Comment by davidferret** [comment]
Same issue happened to me so i used the restore point, I downloaded it offline, i will try with internet tonight and see if it works

**Comment by davidferret** [comment]
With internet it worked

**Comment by Zanut123** [comment]
how i can avoid the internet is disabled during the download

**Comment by ImSwordQueen** [comment]
You need an internet connection at the start of setup (before stage 3) as it is required for downloading the symbols off microsoft's servers
