### ISSUE TITLE
Old Win + Tab (Flip 3D) be added in a future release

### ISSUE THREAD

**Issue by AdityaKKhullar** [ImSwordQueen/Win10to7Issues#16]
Through a windhawk mod, the old Win 7 Alt + Tab and Win + P menus work properly, however, is there a possibility of the old Win + Tab (Flip 3D) to come in a future release? (Also add the old Alt + Tab and Win + P menus by default?)

**Comment by ImSwordQueen** [comment]
Impossible to bring back.
