### ISSUE TITLE
large buttons

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#17]
**Describe the bug**
> A clear and concise description of what the bug is:

Window buttons are big

Description ....

sometimes window buttons are large unlike actual windows 7 ones.

![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/145279552/2735a4c5-36a1-4347-b731-867a4c7803f5)

**To Reproduce**
> Steps to reproduce the behavior:

I'm sure somethings causing it but it's seemingly random

Description ....

/\

**Screenshots**
> If applicable, add screenshots to help explain your problem:

its random

**Additional information (please complete the following information):**
 > OS Version : 
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/145279552/e7e65f3e-befb-42e0-ad99-289548f2228b)

 > Transformation Pack Version : don't know how I check

**Additional context**
May be a windhawk problem if I had to guess.

**Comment by N0VA-The-Git-User** [comment]
?

**Comment by sawyerthemiller** [comment]
Same issue. same os build. I ended up keeping everything else but switching back to openshell start and windowblinds (for most apps) and suprisingly dwmblurglass works with both

**Comment by N0VA-The-Git-User** [comment]
I would use windowsblinds but roblox detects it as a cheating software :(

**Comment by ImSwordQueen** [comment]
The Windhawk mod that restores the caption button isn't working right. You can copy dwmcore and udwm symbols from DWMBlurGlass inside the Windhawk symbols folder or the better option would be to install [AWM ](https://github.com/Dulappy/aero-window-manager) instead of using the Windhawk mod altogether

**Comment by N0VA-The-Git-User** [comment]
I found out a temporary fix. I just need to wait a little when I turn my computer on lol.

**Comment by N0VA-The-Git-User** [comment]
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/145279552/e516960b-1c52-4649-a707-30fc879bdfbb)
