### ISSUE TITLE
Aero buttons and thick borders gone after windows update.

### ISSUE THREAD

**Issue by RumyJCR** [ImSwordQueen/Win10to7Issues#18]
**Describe the bug**
> A clear and concise description of what the bug is:

After updating windows (i didnt want to) the buttons started looking flat again, they look like windows 8 now, also the thick borders arround the windows dont appear, including the hidden icons on the taskbar
I honestly dont know how to fix this, do i have to reinstall this?

**To Reproduce**
> Steps to reproduce the behavior:

Update windows 10 to the latest version while the pack is installed

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![Captura de pantalla (23)](https://github.com/ImSwordQueen/Win10to7Issues/assets/120068612/a151aa56-896c-456b-b5d2-f0abede8d573)

**Additional information (please complete the following information):**
 > OS Version : [Windows 10 22H2 19045.4529]
 > Transformation Pack Version : [3.5]

**Additional context**

A windows update installed when i restarted my pc to install a com emulator, i have no idea how to disable windows updates.

**Comment by ImSwordQueen** [comment]
Windows update replaces certain modified system files when you update windows. Uninstall the pack and reinstall it again.
