### ISSUE TITLE
Add an option to enable Windows 7 Logon UI

### ISSUE THREAD

**Issue by ValeraDX** [ImSwordQueen/Win10to7Issues#19]
**Solution**
> In order to achieve the old winlogon we could use [ConsoleLogonHook](https://github.com/wiktorwiktor12/ConsoleLogonHook).

**Reason to add**
> Old Windows Login Screen makes the overall recreation more accurate.

**Describe alternatives you've considered**
> There is also this ClassicLoginShell fork that can be found [here](https://winclassic.boards.net/thread/1657/vista-login-screen-forked-cls) (on the last page). Sadly, I couldn't find more information about ClassicLoginShell and the Windows versions it supports.

**Additional context**
ConsoleLogonHook works only for Windows 10 version 20H1-22H2 (and its Windows 10 LTSC 2021 counterpart) it shouldn't be much of an issue, considering that the transformation pack is already limited to those versions. Furthermore, we could just grey out this version in the installer if a never version of Windows is detected. Another important thing is that Microsoft accounts might be buggy and the CTRL+ALT+DEL requirement is not fully implemented.

**Comment by ImSwordQueen** [comment]
ConsoleLogonHook will be added in a future release when the project will be more stable and more feature complete

**Comment by ImSwordQueen** [comment]
Added in 3.5.2 as an optional extra
