### ISSUE TITLE
Pre-install Windows Media Center in the next release

### ISSUE THREAD

**Issue by AdityaKKhullar** [ImSwordQueen/Win10to7Issues#23]
Not sure if this request is too popular, but WMC is a great software to watch pre-recorded TV and movies and all. I know it has troubles working properly in the latest builds of W10 and 11, but is it possible that it be included with the next release in the installer itself?

**Comment by ImSwordQueen** [comment]
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/52015098/4c7ba4d3-46f1-49b7-8400-7022976a7f70)
