### ISSUE TITLE
Error when installing the transformation pack

### ISSUE THREAD

**Issue by milesprower2293** [ImSwordQueen/Win10to7Issues#24]
**Describe the bug**
> when i was installing the transformation pack the 3rd phase of setup got stuck at 50% and it displayed an error message:

Description ....

**To Reproduce**
> installing the transformation pack:

Description ....

**Screenshots**
> ![20240706_192658.jpg](https://github.com/ImSwordQueen/Win10to7Issues/assets/131640765/59973224-2508-440c-adb8-4d2b36bd1c75)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 Build 19045.3803
 > Transformation Pack Version 3.5.1

**Comment by ImSwordQueen** [comment]
how much available disk space do you have on the windows partition

**Comment by milesprower2293** [comment]
> how much available disk space do you have on the windows partition

47.4 GB free of 121 GB

**Comment by ImSwordQueen** [comment]
Did you tweak anything before installing the pack? any extra modifications (debloat scripts, etc...)?

**Comment by ImSwordQueen** [comment]
I can't sadly replicate the issue and there hasn't been any activity in the last 3 days so i'm closing this issue.
