### ISSUE TITLE
Computer updated, reinstalled, this is what it looks like now.

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#27]
![image](https://github.com/user-attachments/assets/fab5c9b5-47ae-4cd2-9c42-62e1c07bb2ed)

![image](https://github.com/user-attachments/assets/ee5da604-d7b4-4fe3-8e5f-b92cf3849363)

My computer updated so I updated the pack and now this happened. any ideas?

![image](https://github.com/user-attachments/assets/0b785412-91c4-4cbf-9fe2-e7ec662a1e60)

**Comment by ImSwordQueen** [comment]
DWMBlurGlass didn't download the symbols and uxtheme got unpatched. I'm not using DWMBlurGlass anymore as of version 3.5.2.
