### ISSUE TITLE
Pink

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#28]
**Describe the bug**
Color is pink and I can't change it

Description ....

**To Reproduce**
idk, i installed 3.5.2 and now my color won't change

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![image](https://github.com/user-attachments/assets/83550aee-1479-4b33-9d3d-5231c7e5b33d)

**Additional information (please complete the following information):**
 > OS Version : 
![image](https://github.com/user-attachments/assets/273a585c-8f7b-4950-bc19-4d0cf5a1823d)

**Additional context**
no

**Comment by aliasmaychange** [comment]
I think it's an issue with OpenGlass, because your transparency isn't working correctly, doesn't even render the blur.

**Comment by ImSwordQueen** [comment]
As per the comment above, OpenGlass seems to not be running on your machine.

**Comment by N0VA-The-Git-User** [comment]
Just had to manually install OpenGlass. Thanks!
