### ISSUE TITLE
Caption Button Size don't work that well.

### ISSUE THREAD

**Issue by VicWondermegaMan** [ImSwordQueen/Win10to7Issues#29]
**The problem**
Sometimes when Aero crashes the caption button size change to default instead of Windows 7

**To Reproduce**
Mostly when it crashes. Last day was because I unplugged the charger and it crashed, then OpenGlass returned but the caption button size didn't

**Screenshots**
![image](https://github.com/user-attachments/assets/7b460c22-19f7-4edf-a14b-ae171f86aa28)

**Additional information:**
 > OS Version : Windows 10 Home Single Language 22H2 10.0.19045.4651
 > Transformation Pack Version : 3.5.2

**Question**
Is there a way to change it to the Windows 7 counterpart instead of just "updating" the transformation pack with the installer everytime this happen?

**Comment by ImSwordQueen** [comment]
Can you check in task scheduler if the "Aero Window Manager" task is running after crashing?

**Comment by ImSwordQueen** [comment]
Edit: i found the issue and i will plan on fixing it
