### ISSUE TITLE
What projects are used in this transformation pack, or is it all original code?

### ISSUE THREAD

**Issue by Darthagnon** [ImSwordQueen/Win10to7Issues#3]
Hello, I found this transformation pack via BobPony on Twitter. It looks very interesting, but I'm hesitant to install a 600 MB black box that potentially changes core parts of Windows.

I've seen references to [DWMBlurGlass](https://github.com/Maplespe/DWMBlurGlass), [Open/ClassicShell](https://github.com/Open-Shell/Open-Shell-Menu), [StartIsBack](https://startisback.com/),  so I'm guessing those are components used by this pack. Is there a list anywhere of all the component parts of this pack?

**Comment by ImSwordQueen** [comment]
The list of components used is in the credits on the pack itself but i will link the ones used in 3.5 (which might change in the future) here:

Aero10 by VaporVance as the main 7 theme
DWMBlurGlass by Maplespe for glass Transparency
StartIsBack++ by Tihiy for the start menu
7+ Taskbar Tweaker by Ramen Software (Only used for the future openshell option)
OldNewExplorer by Tihiy for the shellstyle uifile loading feature
7 Games Pack/Classic Calculator by Winaero
Windows Desktop Gadgets by Gadgets Revived
Open Shell (The option to use openshell isn't fully finished and it's disabled)
Windows Media Center by GaRyan2
Windhawk by Ramen Software (+ others for the mods included in windhawk)
Resource Hacker by Angus Johnson (Icon patching)
7z by 7-Zip
