### ISSUE TITLE
dark window blur

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#31]
**Describe the bug**
> A clear and concise description of what the bug is:
the clear part of a window is dark and I can't change it

Description ....

**To Reproduce**
> Steps to reproduce the behavior:
idk 

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

https://github.com/user-attachments/assets/b2e0417e-a7af-4b62-859c-2ee4f07ba184

**Additional information (please complete the following information):**
 > OS Version : 
[Removed for privacy reasons]

 > Transformation Pack Version :3.5.2

**Additional context**
It was pink but I installed OpenGlass and it started working BUT it's really dark. Doesn't matter what is behind it.

**Comment by ImSwordQueen** [comment]
OpenGlass was already installed by the TP but didn't run initially. Due to the specific version of OpenGlass that the pack uses i can really help you here.

**Comment by N0VA-The-Git-User** [comment]
Found a fix! needed to manually install OpenGlass legacy version 1.1 manually.
