### ISSUE TITLE
Foward and Backward page buttons on file explorer are missing.

### ISSUE THREAD

**Issue by DrWafflePhD** [ImSwordQueen/Win10to7Issues#32]
**Describe the bug**
> A clear and concise description of what the bug is: the "foward and backward page" buttons are missing from the file explorer and control panel.

**To Reproduce**
> Steps to reproduce the behavior: Install the pack, disable backtostart, open file explorer.

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![image](https://github.com/user-attachments/assets/142af76c-9dcd-4753-bac4-e0ec156e00ac)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 10 Pro 2022 22H2 19045.4717]
 > Transformation Pack Version : 3.5.2

**Additional context**
Clicking the buttons don't do anything, it's not just a missing icon but the entire function isn't present.

**Comment by ImSwordQueen** [comment]
Try reinstalling aerexplorer thru windhawk again.

Strangely, some of your icons didn't apply correctly too.

**Comment by DrWafflePhD** [comment]
This did not work, ive also tried reinstalling the pack and the buttons still dont appear. :/

**Comment by ImSwordQueen** [comment]
OldNewExplorer is included the pack because of it's functionality to load stuff from shellstyles. but all the functions of it were never enabled. strange.
