### ISSUE TITLE
Making native features from Windows 7

### ISSUE THREAD

**Issue by No-system32-redirect** [ImSwordQueen/Win10to7Issues#35]
- Windows 7 Narrator was replaced instead Original.
- Windows 7 Sound Recorder was replaced instead from Windows 8 (I almost check from system32 and that is file version of Windows 8 indication.)
- Windows 7 XPS Viewer was replaced instead from Windows 8 (like Sound Recorder from Windows 8 as file version indication.)
- Windows 7 Snipping Tool was replaced instead Snipping Tool from Windows 10 10240.
- Windows 7 Remote Desktop Connection was replaced instead last update of Windows 10 RDC.
- Windows 7 Help and Support was replaced instead of 7989 by default, and also more add Windows 7 help page.
- Adding Tablet PC Input Panel.
- Adding Games Explorer and also adding right side menu "Games" on StartIsBack++.
- Adding Windows Jurnal.
- Adding Sticky Notes by default instead Extras folder.
- Adding Windows Defender from Windows 7 (what is a replacing Windows Security by default or not?)
- The Shutdown Dialog has been replaced with Windows 7 counterpart (important.)
- The Windows DVD Maker it is can run after your looking source how to make MPEG-2 encoder was installed by default.
- The "Alt+F4" dialog has been modified to more accurate to it's Windows 7 counterpart, it is one the font was changed and the window size was been slighty reduced (important, I look is wasn't changing dialog after latest update.)

**Comment by ImSwordQueen** [comment]
1. Tried and it broke more things
2. Looks and works the same
3. Looks and works the same
4. The Windows 10 version has more functionality than the 7 version that some people might want.
5. No.
6. No. (Too many registry keys.)
7. Nobody has ported those yet.
8. No. (Read N.6)
9. No.
10. No.
11. No. (Useless)
12. I don't think it is moddable. I'm not sure.
13. No. (It could be considered piracy and it makes the pack at risk for no reason.)
14. ???

**Comment by OliviaIsTyping** [comment]
> * Windows 7 Narrator was replaced instead Original.
> 
>     * Windows 7 Sound Recorder was replaced instead from Windows 8 (I almost check from system32 and that is file version of Windows 8 indication.)
> 
>     * Windows 7 XPS Viewer was replaced instead from Windows 8 (like Sound Recorder from Windows 8 as file version indication.)
> 
>     * Windows 7 Snipping Tool was replaced instead Snipping Tool from Windows 10 10240.
> 
>     * Windows 7 Remote Desktop Connection was replaced instead last update of Windows 10 RDC.
> 
>     * Windows 7 Help and Support was replaced instead of 7989 by default, and also more add Windows 7 help page.
> 
>     * Adding Tablet PC Input Panel.
> 
>     * Adding Games Explorer and also adding right side menu "Games" on StartIsBack++.
> 
>     * Adding Windows Jurnal.
> 
>     * Adding Sticky Notes by default instead Extras folder.
> 
>     * Adding Windows Defender from Windows 7 (what is a replacing Windows Security by default or not?)
> 
>     * The Shutdown Dialog has been replaced with Windows 7 counterpart (important.)
> 
>     * The Windows DVD Maker it is can run after your looking source how to make MPEG-2 encoder was installed by default.
> 
>     * The "Alt+F4" dialog has been modified to more accurate to it's Windows 7 counterpart, it is one the font was changed and the window size was been slighty reduced (important, I look is wasn't changing dialog after latest update.)

I had a stroke reading this
