### ISSUE TITLE
windows 7 logon screen question

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#37]
How to I change the default flower image on the windows 7 login?

**Comment by aliasmaychange** [comment]
User account settings, no need to thank me.

**Comment by N0VA-The-Git-User** [comment]
> User account settings, no need to thank me.

I don't think you have used the windows 7 login thing before

**Comment by aliasmaychange** [comment]
I am using the the latest 10to7, you just have a skill issue. Anyways, go to the Settings app, and check account settings, from there, change the account picture to anything.

**Comment by Umbrella-TEC** [comment]
> How to I change the default flower image on the windows 7 login?

I believe this pack uses https://github.com/wiktorwiktor12/ConsoleLogonHook. This modification does not provide for changing the image (the image is embedded in the dll, you can change it via reshacker). I hope in the future they will add changing the image via settings.

**Comment by aliasmaychange** [comment]
Dude, it actually does change the profile pic, y'all are just using the default profile pic.

**Comment by ImSwordQueen** [comment]
If you mean the profile picture: https://www.wikihow.com/Change-a-User-Account-Picture-in-Windows-10

If you mean the Login wallpaper in CLH: https://www.howtogeek.com/112110/how-to-set-a-custom-logon-screen-background-on-windows-7/
