### ISSUE TITLE
No taskbar "texture" shine effect

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#39]
![image](https://github.com/user-attachments/assets/922c8d20-1be2-4f42-8cdc-62a86b1df599)
This taskbar has that sort of shine effect on it.

![image](https://github.com/user-attachments/assets/a8592024-0550-47c7-95fc-4c3719797b81)

Mine doesn't. It was working before, but after I updated the pack, now it doesn't have that shine effect.

**Comment by N0VA-The-Git-User** [comment]
I found the issue. Legacy openglass, what I use, didn't have that shine effect. Regular OpenGlass does. However, that leads back  #31 where the windows are dark. I will try other solutions and will say when I find a fix.

**Comment by ImSwordQueen** [comment]
> I found the issue. Legacy openglass, what I use, didn't have that shine effect. Regular OpenGlass does. However, that leads back #31 where the windows are dark. I will try other solutions and will say when I find a fix.

My version of OpenGlass legacy has it. I don't know how yours does not.

**Comment by AdityaKKhullar** [comment]
> > I found the issue. Legacy openglass, what I use, didn't have that shine effect. Regular OpenGlass does. However, that leads back #31 where the windows are dark. I will try other solutions and will say when I find a fix.
> 
> My version of OpenGlass legacy has it. I don't know how yours does not.

Is there any real benefit of using OpenGlass over DWMBlurGlass? Cause I swear DWMBlurGlass was way more stable (could be me)

**Comment by N0VA-The-Git-User** [comment]
Found a fix! the fix:     DWMblurglass

reinstalled it and it works so much better and simpler

also here's this: https://github.com/ALTaleX531/OpenGlass/issues/22
