### ISSUE TITLE
Chrome and UWP borders

### ISSUE THREAD

**Issue by the-poor-gamer-124** [ImSwordQueen/Win10to7Issues#4]
Both chrome and uwp borders are weird 

![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/46222936/c032c487-a735-42ed-a9fc-78e2a7383099)

**Comment by ImSwordQueen** [comment]
UWP titlebars are rendered differently than the normal titlebars. There is a Windhawk mod that brings the native ones but it only has the close button for all windows.

Meanwhile Chromium (Google Chrome, Microsoft Edge and Brave) and Firefox (Past version 115) removed the ability to render the native titlebar opposed to their custom implementation. The only way to get native titlebars on a browser is to use a fork of chromium that still has it or use firefox ESR 115.

**Comment by the-poor-gamer-124** [comment]
Not possible to exclude thos from titlebar mod?

**Comment by the-poor-gamer-124** [comment]
isnt it possible to simply exclude some apps from the aero glass?
