### ISSUE TITLE
can't reinstall the transformation pack after running system file checker

### ISSUE THREAD

**Issue by autoboy6446** [ImSwordQueen/Win10to7Issues#44]
**Describe the bug**
> "An error occured restoring Windows." screen pops up after restarting when trying to update/uninstall the transformation pack after running system file checker

Description
 i wanted to reinstall the transformation pack because i was having issues with it but them it takes me to a windows boot manager screen. if i press enter windows boots up fine, but i cant uninstall the transformation pack at all.

**To Reproduce**
> Steps to reproduce the behavior: run sfc /scannow with the transformation pack installed, restart when system file checker is done, after restart try updating or uninstalling the transformation pack, wait until it restarts, and it should take you to a windows boot manager screen stating that there was an error when restoring windows, and that it's either the programs problem or a problem with your windows install, which then states that if booting into windows itself fails is to boot into the recovery environment to restore via restore point.

**Screenshots**
> i described what it looked like at the end of the reproduction steps. check additional context for exact error information.

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 2021 21H2 19044.1288
 > Transformation Pack Version : 3.5.2

**Additional context**
back when the transformation pack worked fine, i was unable to play some videos through the explorer, i would get an error saying "Server execution failed.". i tried running sfc /scannow in which hopefully it would get rid of this issue, but no. it got rid of the aero style and everything else and it all reverted to metro. i thought i could try reinstalling the transformation pack again, therefore i tried that. after the restart, a windows boot manager error gets displayed to me with the error saying;

"Task: Restore pre-transformation files and settings and uninstall 

System.ArgumentNullException: Value cannot be null.
Parameter name: array
at System.Array.Reverse(Array array)
at Win10To7_Setup_Mode_Phases.RestorationForm.RestorationPhase3()"

this however as i said before, does not brick my windows install. when i press the enter button to restart, windows boots up perfectly fine albeit with the metro style back like if i never installed it in the first place. im just unable to uninstall the transformation pack at all if i want to reinstall this.

**Comment by ImSwordQueen** [comment]
Can you try deleting  `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Win10to7` in regedit and `C:\Windows\Win10to7` in explorer and try to run the transformation pack again?

**Comment by ImSwordQueen** [comment]
I guess the issue has been resolved because there hasn't been any new update. If it isn't resolved you can reopen this issue
