### ISSUE TITLE
The "Alt+F4" dialog has been modified to more accurate to it's Windows 7-like

### ISSUE THREAD

**Issue by No-system32-redirect** [ImSwordQueen/Win10to7Issues#47]
Can do the "Alt+F4" dialog can modified to more accurate to it's Windows 7-like?
**From this:**
![Shutdown Dialog](https://github.com/user-attachments/assets/6cb11d89-feb2-439c-9fa6-ea19ad340f4b)
**To this:**
![Shutdown Dialog 1](https://github.com/user-attachments/assets/3f6871a4-372b-4dda-bd0a-09703a906916)
It is one the font must changed and the window size must slightly reduced.

**Comment by AdityaKKhullar** [comment]
at this point you're just nitpicking cause I never noticed that, aside from size it is identical
