### ISSUE TITLE
Updating Windows bricks computer (apparently)

### ISSUE THREAD

**Issue by olibobpri** [ImSwordQueen/Win10to7Issues#55]
**Describe the bug**
> A clear and concise description of what the bug is:
enderboy3 on DeviantArt commented that "It bricked my computer after an update"

**To Reproduce**
> Steps to reproduce the behavior:
Update your computer whilst using this transformation pack

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 10 Pro 22H2 19045.4651]
 > Transformation Pack Version : [e.g. 3.5]

**Additional context**

**Comment by aliasmaychange** [comment]
Why did you even do that in the first place? You aren't supposed to do that, at least with the non-safe version (I've heard a safe version is coming), you need updates disabled.

**Comment by olibobpri** [comment]
I never said I did. I made an issue regarding what enderboy3 on DeviantArt commented: "It bricked my computer after an update"

**Comment by ImSwordQueen** [comment]
It shouldn't even brick itself as if microsoft reverts uxtheme then the default 10 theme should replace the 7 one

**Comment by ImSwordQueen** [comment]
And can't repro because i tried a wild range of updates (from jan 2024 to july 2024) and none of those truly bricked a 21H2to7 install.
