### ISSUE TITLE
Window Colors / Transparency only works on one monitor

### ISSUE THREAD

**Issue by umbreonben** [ImSwordQueen/Win10to7Issues#59]
**Describe the bug**
> A clear and concise description of what the bug is:

I have 2 monitors and on my second one the transparency and the custom set color is working properly and on the other one it's just black without any transparency.

**To Reproduce**
> Steps to reproduce the behavior:

Installing the pack while having 2 monitors I guess

**Screenshots**
> If applicable, add screenshots to help explain your problem:

First Monitor:
![image](https://github.com/user-attachments/assets/0fd61b26-72c6-447c-95ff-a2234f1d4ff8)
![image](https://github.com/user-attachments/assets/98e9e615-c5dc-41e3-954f-8de8a4892b40)

Second Monitor:
![image](https://github.com/user-attachments/assets/3ffbc2d1-9fe9-44c5-8eab-d6795e1ae2bd)
![image](https://github.com/user-attachments/assets/e1572116-4301-45dc-9a30-6d0cab935ec9)

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 10 Pro 22H2 19045.4717]
 > Transformation Pack Version : Not sure where I can find it but I installed the latest one uploaded on August 1, 2024

**Additional context**
When a notification pops up on the first monitor it suddenly works, but as soon as the notification goes away the transparency and color is gone again.

**Comment by ImSwordQueen** [comment]
It seems to be an OpenGlass issue. You should open an issue here instead: [alTaleX531/openGlass](https://github.com/ALTaleX531/OpenGlass/)

**Comment by umbreonben** [comment]
They said: 

> For multiple monitors, use the master branch instead of the legacy branch.

https://github.com/ALTaleX531/OpenGlass/issues/23

Is there anything I can do here?

**Comment by ImSwordQueen** [comment]
> They said:
> 
> > For multiple monitors, use the master branch instead of the legacy branch.
> 
> [ALTaleX531/OpenGlass#23](https://github.com/ALTaleX531/OpenGlass/issues/23)
> 
> Is there anything I can do here?

I guess for now you can use https://github.com/tetawaves/OpenGlass/releases/tag/v1.2-glow if you want glow on the master branch. I can't do anything more here sadly.

**Comment by ImSwordQueen** [comment]
Update on this: https://github.com/ALTaleX531/OpenGlass/issues/30

This workaround might work to fix the issue
