### ISSUE TITLE
Start menu pins disappear after installing/updating

### ISSUE THREAD

**Issue by thecg19** [ImSwordQueen/Win10to7Issues#6]
When using StartIsBack, any pinned apps will disappear after installing or updating the transformation pack. But the shortcuts still exist in the folder (C:\Users\User\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu)

Windows 10 LTSC IoT 2021
TP Version: 3.5

**Comment by ImSwordQueen** [comment]
This issue should be fixed in the next update of the pack
