### ISSUE TITLE
Disabling the Windows 8+ OSD

### ISSUE THREAD

**Issue by No-system32-redirect** [ImSwordQueen/Win10to7Issues#62]
I want Disabling the OSD? even i pressing the volume on the keyboard shortcut every time and always shown them.
So is not like Windows 7 transform prior, but whether is can find source them?

![OSD](https://github.com/user-attachments/assets/9badd578-a026-45c1-bdb8-03eea70b8978)

**Comment by ImSwordQueen** [comment]
https://letmegooglethat.com/?q=Disable+Windows+8+OSD+site%3Awinclassic.net
