### ISSUE TITLE
W7 Trans Pride Wallpaper

### ISSUE THREAD

**Issue by nullgato** [ImSwordQueen/Win10to7Issues#64]
I'm sorry if this doesn't belong as an issue, I just felt it was the best way to ask since your DA comments are loaded with a lot of stuff I wouldn't necessarily want to look at either. 

I was hoping I could be pointed to the wallpaper that you credit on the DA post, I did try to find it myself but wasn't able to. I checked the personalization menu. I tried to search the artist you credited. I even spent about 30 minutes just scrolling through a "windows 7 trans pride wallpaper" image search, but I ultimately couldn't find anything. It's okay and totally understandable if this isn't a good use of time, please don't bother if you don't have the spoons for it you can just close this. If you are willing though, I'd really appreciate it because the wallpaper looked so pretty and there are other pretty ones but they don't feel as 7-y as the one you had in the DA image. :3

**Comment by ImSwordQueen** [comment]
You can find the original wallpaper here: https://discord.com/channels/1170481985664340112/1268386531597352961 (https://discord.gg/vczkvxncqu) 

but if you want the wallpapers (All credits go to marbles0976) :

Windows 7: https://media.discordapp.net/attachments/1268386531597352961/1268386532255989802/IMG_6728.png?ex=66c9e642&is=66c894c2&hm=dfd6eac81a47259497e3923020fe3de8a46f606dbe804eaf128440edd89e0f1c&=&format=webp&quality=lossless (Send the link in a discord chat to re-generate the link if it expires)

Windows 7 Starter: https://media.discordapp.net/attachments/1268386531597352961/1268407007883563088/Untitled1517_20240731200801.png?ex=66c9f954&is=66c8a7d4&hm=f8a962202ada8df9fa3c845c2944d4c74cfb8c34c5a50e86000b21c525b59445&=&format=webp&quality=lossless (Send the link in a discord chat to re-generate the link if it expires)

Windows 8 Flower: https://media.discordapp.net/attachments/1268386531597352961/1268402200913248256/IMG_6733.png?ex=66c9f4da&is=66c8a35a&hm=8804215634a77a854f582c6425ba05d8b27f6f9ef2a254556a666756a40767c1&=&format=webp&quality=lossless (Send the link in a discord chat to re-generate the link if it expires)

**Comment by nullgato** [comment]
Thank you, I appreciate it so much! (Sorry if this messes up the issue close, still learning GitHub)

**Comment by illusion0001** [comment]
Reuploading in case someone don't have discord to regenerate the links

<details><summary>
Windows 7 (Click to expand)
</summary>

![IMG_6728](https://github.com/user-attachments/assets/33e87b11-27e8-406e-ba95-fb935f99b708)

</details>

<details><summary>
Windows 7 Starter (Click to expand)
</summary>

![Untitled1517_20240731200801](https://github.com/user-attachments/assets/e1554b6b-43e1-4f40-877d-8f0f787ad5dd)

</details>

<details><summary>
Windows 8 Flower (Click to expand)
</summary>

![IMG_6733](https://github.com/user-attachments/assets/325a7752-291e-460c-ae59-abccd462c992)

</details>
