### ISSUE TITLE
taskbar and window title bar is black and not transparent

### ISSUE THREAD

**Issue by Wyind** [ImSwordQueen/Win10to7Issues#66]
**Describe the bug**
when a white window is not behind the taskbar, start menu, or titlebar, it will simply turn black and not transparent. having a custom color or really any color applied to another theme will yield the same result. turns back when windows screenshot tool (Win + Shift + S) is turned on it will become transparent again. 
Description ....

**To Reproduce**
> Steps to reproduce the behavior: create a custom theme with a custom color with transparency in windows settings.

**Screenshots**
attached

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 22H2
 > Transformation Pack Version : the one posted on aug 1st, 2024 (no clue how to check)

**Comment by ImSwordQueen** [comment]
Temp solution: https://github.com/ImSwordQueen/Win10to7Issues/issues/59#issuecomment-2373889385
