### ISSUE TITLE
Replace Defender tray icon with icons from MS Security Essentials

### ISSUE THREAD

**Issue by FanACYT** [ImSwordQueen/Win10to7Issues#67]
**Describe the solution you'd like**
> Add a option or something to replace the Defender tray icon

**Your reason (tell us why we need it)**
> Have figured out a way to replace the Defender Tray icon

**Describe alternatives you've considered**
> none

**Additional context**
What I did was replace the icons on the SecurityHealthSSO.dll file in System32

![image](https://github.com/user-attachments/assets/e3ca0384-99d5-4005-8c3d-ba302cb76fc0)

**Comment by ImSwordQueen** [comment]
I could add this as an extra. Thanks for the suggestion
