### ISSUE TITLE
Flickering when closing control panel while in personalization menu/going back to the previous menu

### ISSUE THREAD

**Issue by uncognic** [ImSwordQueen/Win10to7Issues#68]
**Describe the bug**
> A clear and concise description of what the bug is: When opening the personalization menu in control panel where all the themes are, closing control panel causes a quick flicker of all monitors.

Description ....

**To Reproduce**
> Steps to reproduce the behavior: Open control panel, navigate to personalization
close window

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : LTSC 2021 21H2 19044.4780
 > Transformation Pack Version : The newest one

**Additional context**

**Comment by ImSwordQueen** [comment]
Try updating aerexplorer to 1.6.4 in windhawk. I believe that fixed it.

**Comment by uncognic** [comment]
Alright thanks lol also can I just rerun the installer if a windows update
reverts some stuff or I want to add something
