### ISSUE TITLE
Notifications to be added to the old Action Center

### ISSUE THREAD

**Issue by AdityaKKhullar** [ImSwordQueen/Win10to7Issues#7]
Hi, so I've been using this mod for the past (3?) days and I have to say I am really impressed with it. However, all the notifications from any apps still come through the Windows 10 notification system, which looks really ugly with the Aero UI. Is it possible, that in a future revision, notifications show up as a "bubble" or "pop-out" or whatever you call it from the old Action Center icon? Thanks :)

**Comment by ImSwordQueen** [comment]
I know there is a tweak to re-enable balloon tips but i chosen not to include it due to them being glitchy and not working as intended a lot of times (for me atleast)

**Comment by AdityaKKhullar** [comment]
Can you let me know of the tweak? I'd love to test it for you and see if it works well so you can implement it in the next build. Thanks?

**Comment by ImSwordQueen** [comment]
https://winaero.com/enable-balloon-notifications-in-windows-10-using-a-registry-tweak

**Comment by AdityaKKhullar** [comment]
Nope, toast notifications still show up and I still don't see balloon ones, tried both regedit and group policy method.

Also, regarding the browser aero, can you put it in the readme that Supermium is the only up-to-date browser (other than 115 ESR) that completely supports aero (after enabling a flag)?

**Comment by AdityaKKhullar** [comment]
Okay, balloon notifications work, but some applications still utilise toast ones. Any way to get them to show balloon notifications?
