### ISSUE TITLE
Please add the ability to change the login screen background with the Windows 7 login screen

### ISSUE THREAD

**Issue by miamunson** [ImSwordQueen/Win10to7Issues#70]
> A clear and concise description of what you want to happen.
I would like the ability to change the login screen background when using the Windows 7 login screen option.

> Briefly describe your reasons for wanting to do this.
It was possible to do this in Windows 7 easily with regedit or gpedit. It's also nice for customization reasons to be able to have your own wallpaper on the login screen.

> A clear and concise description of any alternative solutions or features you've considered.
I've tried looking for where the background is stored for the transformation pack in C:\Windows to manual change it, to no avail. I've also tried setting an image in the photos app on Windows 10. For now, I use the Windows 10 login screen so I can change the background.

**Comment by ImSwordQueen** [comment]
https://github.com/ImSwordQueen/Win10to7Issues/issues/37#issuecomment-2273785780
