### ISSUE TITLE
Windows theme issue | Dark and light mode

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#71]
![image](https://github.com/user-attachments/assets/097cd205-2bee-4d1f-88ba-0fff8c910547)
Trying to use light mode but this happens with a lot of things. Dark mode works fine, may not be a 10to7 problem.

**Comment by AdityaKKhullar** [comment]
+1

**Comment by N0VA-The-Git-User** [comment]
> +1

You have the same issue?

**Comment by ImSwordQueen** [comment]
Strange. Can you send me the aero.msstyles in c:\Windows\Resources\Themes\Aero7?

**Comment by N0VA-The-Git-User** [comment]
> Strange. Can you send me the aero.msstyles in c:\Windows\Resources\Themes\Aero7?

https://cdn.discordapp.com/attachments/1094515237144756224/1280299227850870844/aero.msstyles?ex=66d79312&is=66d64192&hm=c096916f7bf5c79f8119139cb7ad015b31ae8456790b6e3739d8341a270991d2&

**Comment by ImSwordQueen** [comment]
> > Strange. Can you send me the aero.msstyles in c:\Windows\Resources\Themes\Aero7?
> 
> https://cdn.discordapp.com/attachments/1094515237144756224/1280299227850870844/aero.msstyles?ex=66d79312&is=66d64192&hm=c096916f7bf5c79f8119139cb7ad015b31ae8456790b6e3739d8341a270991d2&

Hm. It seems fine. Do you have secureuxtheme installed by any chance?

**Comment by N0VA-The-Git-User** [comment]
> > > Strange. Can you send me the aero.msstyles in c:\Windows\Resources\Themes\Aero7?
> > 
> > 
> > https://cdn.discordapp.com/attachments/1094515237144756224/1280299227850870844/aero.msstyles?ex=66d79312&is=66d64192&hm=c096916f7bf5c79f8119139cb7ad015b31ae8456790b6e3739d8341a270991d2&
> 
> Hm. It seems fine. Do you have secureuxtheme installed by any chance?

yes

**Comment by ImSwordQueen** [comment]
Probably ultrauxtheme patcher got uninstalled and so when you try to switch themes it won't switch because the theme is unsigned (I never signed them for secureux)

**Comment by N0VA-The-Git-User** [comment]
> Probably ultrauxtheme patcher got uninstalled and so when you try to switch themes it won't switch because the theme is unsigned (I never signed them for secureux)

Oh, how would I fix that?

**Comment by ImSwordQueen** [comment]
Open the themetool.exe program that came from https://github.com/namazso/SecureUxTheme, select the "Windows 7" theme and click apply "patch" or "apply and patch"

**Comment by ImSwordQueen** [comment]
was this resolved?

**Comment by N0VA-The-Git-User** [comment]
> was this resolved?

Sorry for the late reply but no, secureXtheme doesn't work at all, and hasn't been fixed yet.

**Comment by ImSwordQueen** [comment]
> > was this resolved?
> 
> Sorry for the late reply but no, secureXtheme doesn't work at all, and hasn't been fixed yet.

the only thing is to see if reinstalling UltraUXTheme from here https://mhoefs.eu/software_uxtheme.php fixes it.
