### ISSUE TITLE
Can't extract using Explorer, Winrar and 7zip

### ISSUE THREAD

**Issue by goodoldweb2013** [ImSwordQueen/Win10to7Issues#72]
**Describe the bug**
> A clear and concise description of what the bug is: I installed 10to7 successfully, but I changed my monitor scaling and it broke alongside the gadgets. I've tried to install the newest version and I can't extract it, it says that the CRC failed on 7zip, and the Explorer simply won't extract it while Winrar says that it can't verify the file.

Description ....

**To Reproduce**
> Steps to reproduce the behavior: Alter the scaling of the apps to 125% while having 1920x1080. Download the 10to7 on DeviantART, then extract.

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem: <img width="427" alt="Sem título" src="https://github.com/user-attachments/assets/720c3c12-09d1-44b0-8452-7d95610d3222">

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 22H2 19045.4474
 > Transformation Pack Version : 3.5.2

**Additional context**
The gadgets and the profile picture at the lock screen are broken when changing the resolution, I've tried to reinstall it again, but it can't extract the pack.

**Comment by ImSwordQueen** [comment]
You are meant to run the transformation pack... not extract it?
