### ISSUE TITLE
Missing Aero Glass blur

### ISSUE THREAD

**Issue by chewchu** [ImSwordQueen/Win10to7Issues#73]
**Describe the bug**
> A clear and concise description of what the bug is:

Missing blur effect in titlebars/windows, they are almost completely transparent and text/images are fully visible behind them. Also, the personalization settings (tinting the color of the Aero Glass) do not seem to work. 

**To Reproduce**
> Steps to reproduce the behavior:

This has happened since I installed the transformation pack. I used DWMBlurGlass before I installed it, but uninstalled it and deleted the relevant files before running 10to7 (it did produce the right blur effect). I'm assuming this is an OpenGlass issue, so I tried to fix it by adding registry keys in HKCU\Software\Microsoft\Windows\DWM. However, there were not only no (or not many?) existing keys added by OpenGlass, but the keys I added (GlassType, RoundRectRadius, GlassOpacity, CustomThemeReflection) had no effect.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

Messy titlebars:
![image](https://github.com/user-attachments/assets/6a851990-1906-47b9-849d-df6bb8f8d478)

Glass should be tinted purple but is still transparent:
![image](https://github.com/user-attachments/assets/01d983c6-f7b5-41f8-a796-b5ba470bff73)

Registry entries for DWM:
![image](https://github.com/user-attachments/assets/4640e884-8223-402e-ab69-565f2b401fc7)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 2021 21H2 19044.4780
 > Transformation Pack Version : 3.5.2

**Additional context**

**Comment by ImSwordQueen** [comment]
Go in task scheduler (%windir%\system32\taskschd.msc /s) and run 000OpenGlass Host and see if that works.

**Comment by chewchu** [comment]
It was already running for me, so I tried stopping and restarting it as well as restarting my computer. Unfortunately there weren't any changes

**Comment by ImSwordQueen** [comment]
Does openglass show any error?

**Comment by chewchu** [comment]
It doesn't show any errors when I stop or start the task, and there is no dumps folder. I also disabled the service and restarted, so it shouldn't have injected anything on startup, and everything looks the same. It seems like it's just not doing anything?

**Comment by ImSwordQueen** [comment]
Hm strange. I would check if changing it from running the task as startup to log in would make any difference.

**Comment by AdityaKKhullar** [comment]
openglass is buggy as hell, dwmblurglass worked better, maybe next update you can give an option for the user to decide which one he/she wants

> Hm strange. You should check if changing it from running the task as startup to log in would make any difference.

**Comment by chewchu** [comment]
> Hm strange. You should check if changing it from running the task as startup to log in would make any difference.

This still did not make a difference, I also reinstalled the transformation pack since it was bugging me and it is behaving the same. Would I be able to safely install DWMBlurGlass if I disable the OpenGlass service?

**Comment by ImSwordQueen** [comment]
> openglass is buggy as hell, dwmblurglass worked better, maybe next update you can give an option for the user to decide which one he/she wants
> 
> > Hm strange. You should check if changing it from running the task as startup to log in would make any difference.

all the previous issues with version 3.5.1 were related to DWMBG. so DWMBG you would get frequent crashes meanwhile with OpenGlass you would not get openglass not hooked into dwm.

**Comment by ImSwordQueen** [comment]
> > Hm strange. You should check if changing it from running the task as startup to log in would make any difference.
> 
> This still did not make a difference, I also reinstalled the transformation pack since it was bugging me and it is behaving the same. Would I be able to safely install DWMBlurGlass if I disable the OpenGlass service?

You should try to reinstall openglass again (by first removing the openglass service). and using the dll that 21H2to7 has instead of the default one.

**Comment by AdityaKKhullar** [comment]
> > openglass is buggy as hell, dwmblurglass worked better, maybe next update you can give an option for the user to decide which one he/she wants
> > > Hm strange. You should check if changing it from running the task as startup to log in would make any difference.
> 
> all the previous issues with version 3.5.1 were related to DWMBG. so DWMBG you would get frequent crashes meanwhile with OpenGlass you would not get openglass not hooked into dwm.

I'm having worse luck with OpenGlass, also it just straight up stops showing the aero blur in a lot of places like when fullscreened and you opening the start button, etc

**Comment by illusion0001** [comment]
Enable transparency in Windows Settings
![image](https://github.com/user-attachments/assets/d02ce350-fa3c-42f5-b902-8f699f40ac53)
![image](https://github.com/user-attachments/assets/8d0ee9ab-6437-4044-8344-9526b9599602)

**Comment by illusion0001** [comment]
Or just enable it during theme install
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"EnableTransparency"=dword:00000001
```

**Comment by ImSwordQueen** [comment]
> Or just enable it during theme install
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize]
> "EnableTransparency"=dword:00000001
> ```

Interesting. i didn't think that was going to disable openglass entirely.
