### ISSUE TITLE
Aero Glass is sometimes black

### ISSUE THREAD

**Issue by uncognic** [ImSwordQueen/Win10to7Issues#74]
**Describe the bug**
> A clear and concise description of what the bug is: 
When alt tabbing into a window, or opening the start menu, the aero parts are black for a split second and then beocme aero

**To Reproduce**
> Steps to reproduce the behavior: 
Alt tab into a window and another a couple of times and you will see it becoming black sometimes.

**Screenshots**
> If applicable, add screenshots to help explain your problem: I cannot, as it does not stay long enough for me to take a screenshot of it

**Additional information (please complete the following information):**
 > OS Version :Windows 10 LTSC 2021 21H2 19044.4780
 > Transformation Pack Version : Latest

**Additional context**
Add any other context about the problem here. I also made the same issue in openglass github.

**Comment by uncognic** [comment]
![image](https://github.com/user-attachments/assets/108385f2-36c2-4072-873a-ca4cedea495d)
i got an image of it

**Comment by ImSwordQueen** [comment]
Do you have a second monitor? There was a bug with multiple monitor setups atm.

**Comment by uncognic** [comment]
I do, it’s a 1360x768 Samsung monitor, I am wondering something though,
this did not happen on my previous windows install, so I wonder what causes
it to glitch this time

**Comment by ImSwordQueen** [comment]
I recently (since version 3.5.2) changed the program that rendered glass transparency from DWMBG to OpenGlass Legacy. which is probably why you are having this issue. It's a known issue reported here: https://github.com/ImSwordQueen/Win10to7Issues/issues/59

**Comment by uncognic** [comment]
I’m not sure if this is the issue, as aero works completely fine on both
monitors, the only issue is that it sometimes flickers black when opening
something that uses aero

**Comment by ImSwordQueen** [comment]
Yeah that's the same issue.

**Comment by uncognic** [comment]
Alright thanks for the help lol
