### ISSUE TITLE
Enabling "Windows 7 Lockscreen" or smth like that, causes Windows to brick.

### ISSUE THREAD

**Issue by kaer1a** [ImSwordQueen/Win10to7Issues#75]
**Describe the bug**
> A clear and concise description of what the bug is:

Selecting the "Windows 7 lockscreen" option causes windows to brick and I don't know why.
Originally I had selected it from the transformation pack and it was working; and then I changed it because it wasn't working properly on my 21:9 monitor.

I had tried to turn it off and reboot and it wouldn't turn the setting off.
I tried to restore from my restore point and it wouldn't do it either.

The result of this caused LogonUI (i think it's called that), to be only in cmd prompt and I still cannot restore via a restore point.

I will most likely have to freshly re-install Windows 10 which sucks but yeah.

By "broken", I didn't think it would brick my install of Windows.

Description ....

**To Reproduce**
> Steps to reproduce the behavior:
Enable W7 Lockscreen
Reboot
Turn it off
And then reboot

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:
I forgot to take a picture but I will provide some tomorrow.

**Additional information (please complete the following information):**
 > OS Version : Windows 10 (22H2)
 > Transformation Pack Version : Latest Version as of the 4th of September

**Additional context**
This isn't anymore context but is it possible to restore from my restore point or will I **have** to freshly re-intsall Windows?

**Comment by kaer1a** [comment]
Also, trying to just turn off the W7 LS doesn't work at all, it says an error about something regarding: "Step 2 couldn't progress" or something like that.

**Comment by ImSwordQueen** [comment]
That's strange. if you can provide more info it would be useful. you can restore the windows 10 one by doing `sfc /scanfile="c:\windows\system32\windows.ui.logon.dll"`

**Comment by ImSwordQueen** [comment]
Okay i now see what's the problem. I'm so sorry for the inconvenience. if you want to fix your current windows install you can do it via sfc /scannow.

**Comment by ImSwordQueen** [comment]
Okay the issue has been resolved with a bandaid fix until the real issue gets resolved in a future update. it shouldn't break when uninstall/customizing the pack anymore.

**Comment by kaer1a** [comment]
this hasn't been fixed on my end despite me running "sfc /scannow" and downloading the latest version of the pack.

the logonui has been fixed but i still cannot restore my system from the uninstaller and the actual windows restore point menu thing.

i got a picture of what the issue says
![IMG_2827](https://github.com/user-attachments/assets/4875b0b1-0f9b-41cc-92b7-dca475bfb524)

**Comment by kaer1a** [comment]
also when the sfc scan completed, half of the win7 stuff was put back to windows 10 and i can't configure this or anything due to this problem

**Comment by ImSwordQueen** [comment]
> also when the sfc scan completed, half of the win7 stuff was put back to windows 10 and i can't configure this or anything due to this problem

Sorry for the late response, The problem comes from the fact that the old installer would uninstall the pack. you can fix that by removing everything in the win10to7 folder and remove the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Win10to7 registry key.

**Comment by ImSwordQueen** [comment]
> > also when the sfc scan completed, half of the win7 stuff was put back to windows 10 and i can't configure this or anything due to this problem
> 
> Sorry for the late response, The problem comes from the fact that the old installer would uninstall the pack. you can fix that by removing everything in the win10to7 folder and remove the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Win10to7 registry key.

or the proper way is to restore an early snapshot via the restore point that 10to7 does before it installs or does anything.

**Comment by ImSwordQueen** [comment]
Any update on this?

**Comment by kaer1a** [comment]
All is good but I haven’t enabled the Win 7 logon screen sinceSent from my iPhoneOn 10 Sep 2024, at 4:48 pm, ImSwordQueen ***@***.***> wrote:﻿
Any update on this?

**Comment by ImSwordQueen** [comment]
> All is good but I haven’t enabled the Win 7 logon screen sinceSent from my iPhoneOn 10 Sep 2024, at 4:48 pm, ImSwordQueen ***@***.***> wrote:﻿ Any update on this? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Okay that's good to know that everything got resolved.

**Comment by kaer1a** [comment]
could you let us know when the win7 logonui is stable to use? From when I had it on originally, the wallpaper on it didn’t display properly on 21:9 (3440x1440) Sent from my iPhoneOn 10 Sep 2024, at 11:57 pm, ImSwordQueen ***@***.***> wrote:﻿

All is good but I haven’t enabled the Win 7 logon screen sinceSent from my iPhoneOn 10 Sep 2024, at 4:48 pm, ImSwordQueen @.> wrote:﻿ Any update on this? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

Okay that's good to know that everything got resolved.

**Comment by ImSwordQueen** [comment]
> could you let us know when the win7 logonui is stable to use? From when I had it on originally, the wallpaper on it didn’t display properly on 21:9 (3440x1440) Sent from my iPhoneOn 10 Sep 2024, at 11:57 pm, ImSwordQueen ***@***.***> wrote:﻿ All is good but I haven’t enabled the Win 7 logon screen sinceSent from my iPhoneOn 10 Sep 2024, at 4:48 pm, ImSwordQueen @.> wrote:﻿ Any update on this? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> Okay that's good to know that everything got resolved. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Right now the version of CLH included is still 1.0.7. The developer of the port hasn't worked on it for a few weeks.
