### ISSUE TITLE
Taskbar window preview does not have aero and overlaps with the blue part

### ISSUE THREAD

**Issue by uncognic** [ImSwordQueen/Win10to7Issues#76]
**Describe the bug**
> A clear and concise description of what the bug is:

When you put your cursor over an app on the taskbar, the preview does not have aero and the window preview itself overlaps with the bottom of the blue part

**To Reproduce**
> Steps to reproduce the behavior:

Open app
Minimize
Hover cursor over it on the taskbar

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![image](https://github.com/user-attachments/assets/58a07a7d-f82d-4fd8-b0cf-89a3261139dc)
![image](https://github.com/user-attachments/assets/5041e8e9-b34c-40b3-94db-81c1fb64fc87)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 2021 21H2 19044.4780
 > Transformation Pack Version :Latest

**Additional context**

**Comment by ImSwordQueen** [comment]
StartIsBack issue. can't do anything about it...

Until Explorer7/ep_taskbar releases
