### ISSUE TITLE
Right Click Properties in My Computer Explorer Opens Resolution Settings instead of System

### ISSUE THREAD

**Issue by illusion0001** [ImSwordQueen/Win10to7Issues#77]
**To Reproduce**

Right click in empty area and Properties in Explorer My Computer window

![image](https://github.com/user-attachments/assets/fbf0ce65-5c44-4b33-9985-bbd2030d9045)

**Comment by ImSwordQueen** [comment]
this is a bug with the CPL reborn mod. It will be fixed in a next update.
