### ISSUE TITLE
rundll32.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by evil-scout** [ImSwordQueen/Win10to7Issues#78]
**Describe the bug**
> After installing the latest update, anytime explorer.exe or the sound devices menu opens, I get a Entry Point Not Found error in relation to C:\ProgramData\Windhawk\Engine\Mods\64\local@waitbmp-loader_590746.dll

**To Reproduce**
> Update from "Fly high" to "Ciao", open explorer.exe or open the sound devices menu.

**Screenshots**
> 
![image](https://github.com/user-attachments/assets/7075e2e8-4ceb-4435-974e-1e23df9cced8)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 LTSC 22H2
 > Transformation Pack Version : 3.5.3

**Additional context**
I actually had an error for the same thing in regards to aeroexplorer, but this was fixed after a reinstall using windhawk.

**Comment by ImSwordQueen** [comment]
Can you try disabling "Please Wait Bitmap Loader" in Windhawk and see if the same issue still happens?

**Comment by ImSwordQueen** [comment]
Also, can you check what version of windhawk are you running? Just to be sure that i didn't mess up anything by updating the windhawk executable.

**Comment by evil-scout** [comment]
Disabling it fixes it, and my version of Windhawk is v1.4.1.. unsure of what it was before sadly

**Comment by ImSwordQueen** [comment]
Okay. I made a mistake and windhawk didn't update during the customization phase. You can update windhawk to 1.5.1 here https://github.com/ramensoftware/windhawk/releases to fix the issue.
