### ISSUE TITLE
Windows updates

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ImSwordQueen/Win10to7Issues#8]
How could I stop my system from updating because of the issue where new updates break the system?

**Comment by AdityaKKhullar** [comment]
I had the same issue, basically uninstalled the theme, updated Windows and reinstalled it. No other alternative.

**Comment by ImSwordQueen** [comment]
> How could I stop my system from updating because of the issue where new updates break the system?

You can look up online ways to disable updates for Windows 10. My preferred method to "delay" updates is to use the tool that chris titus made that you can find here: https://christitus.com/windows-tool/

**Comment by N0VA-The-Git-User** [comment]
> > How could I stop my system from updating because of the issue where new updates break the system?
> 
> You can look up online ways to disable updates for Windows 10. My preferred method to "delay" updates is to use the tool that chris titus made that you can find here: https://christitus.com/windows-tool/

MY COMPUTER JUST AUTO UPDATED WHILE I WAS AWAY😭☠️ I'm praying it doesn’t break🙏

**Comment by N0VA-The-Git-User** [comment]
alr we good just need to reinstall
