### ISSUE TITLE
Basic theme from Windows 7

### ISSUE THREAD

**Issue by uncognic** [ImSwordQueen/Win10to7Issues#80]
**Describe the solution you'd like**
> Basic theme from Windows 7

**Your reason (tell us why we need it)**
> The pack will be more complete with it, and some people also prefer the basic theme look from Windows 7. There are also many ways to implement it, like spddl/disabledwmactivitys or Windhawk mods

**Describe alternatives you've considered**
> None

**Additional context**

**Comment by aliasmaychange** [comment]
BasicThemer is already included as a Windhawk mod.

**Comment by uncognic** [comment]
That's for secure desktop/UAC only

**Comment by ImSwordQueen** [comment]
Basic theme support will come with ex7 support (and possibly ep_taskbar too)

**Comment by uncognic** [comment]
Thank you
