### ISSUE TITLE
5 bar Wi-Fi icon not loading, stuck on previous icon

### ISSUE THREAD

**Issue by miamunson** [ImSwordQueen/Win10to7Issues#81]
> A clear and concise description of what the bug is:

The 5 bar wi-fi icon in the taskbar does not load and leaves the wi-fi icon stuck on whatever the previous icon was.

> Steps to reproduce the behavior:

Connect to 5 bar wi-fi network, wi-fi icon will change to all empty bars with blue spinning circle. Once connected, it will be stuck on the blue circle. Additionally, if move to a location with 4 bars, the icon will change to 4 bars but will not change back to 5 bars.

> If applicable, add screenshots to help explain your problem:

Image 1: Currently connected to 5 bar network, icon in taskbar shows 4 (names blacked out for privacy)
![1](https://github.com/user-attachments/assets/0006aa77-0ffc-4ef7-8ab9-9a165fc25d79)

Image 2: Disconnected from network, icon changes to disconnected icon.
![2](https://github.com/user-attachments/assets/be07953f-64eb-434f-8bc6-4576b98f6a00)

Image 3: Re-connected to 5 bar network, icon stuck on spinning blue circle
![3](https://github.com/user-attachments/assets/88949c23-bf9e-4c56-81c1-dc145c1f8acf)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Enterprise 19045.4780
 > Transformation Pack Version : 3.5.3 - "Ciao!"

I am using the small taskbar, I do not know if this affects icons. I am also using 7+ taskbar tweaker to decrease the space between icons, and tclock64 to have date on small taskbar.

**Comment by ImSwordQueen** [comment]
can you try this pnidui instead of the one from system32? 
[pnidui.zip](https://github.com/user-attachments/files/16947342/pnidui.zip)

**Comment by miamunson** [comment]
that one seems to work, icon is showing up properly
![image](https://github.com/user-attachments/assets/39889f38-84e7-4323-9468-fa7f2b9f2896)
