### ISSUE TITLE
explorer7 support?

### ISSUE THREAD

**Issue by saulcheeseman** [ImSwordQueen/Win10to7Issues#82]
**Describe the solution you'd like**
> For explorer7 to be added

**Your reason (tell us why we need it)**
> To make the Windows 7 immersion better.

**Describe alternatives you've considered**
> StartIsBack is a good alternative, but it's much nicer to have the real thing.

**Link**
> [explorer7](https://winclassic.net/thread/2588/explorer7-windows-explorer-10-11)

**Comment by ImSwordQueen** [comment]
![image](https://github.com/user-attachments/assets/bb74553c-90be-4725-ad6e-62729712b847)
