### ISSUE TITLE
where are icons stored?

### ISSUE THREAD

**Issue by bonzijuse** [ImSwordQueen/Win10to7Issues#83]
i have been trying to create a library for the classic games and have it show the proper icon rather than just a folder, i got the icon on another folder, and after that the available icon set changed from win7 icons to a mix of win95, winxp, win7, and win10 icons. its getting icons from shell32.dll, the win7 icons are very incomplete not but only in the icon chooser, everything else is still fine. am i stupid?

**Comment by ImSwordQueen** [comment]
Most icons that are used by windows are stored in imageres.dll in c:\Windows\System32\Imageres.dll. (The real icon location is in C:\Windows\SystemResources\imageres.dll.mun
