### ISSUE TITLE
Oversight in Romanian localization

### ISSUE THREAD

**Issue by aliasmaychange** [ImSwordQueen/Win10to7Issues#87]
**Describe the bug**
> A clear and concise description of what the bug is:

Description: While I do not speak Romanian, I noticed that the lines are that of stock 8.1. This is not an issue in any other available localization pack.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

Note the lack of the Magnifier link.
![зображення](https://github.com/user-attachments/assets/dfa6a692-e63a-48cb-b0c1-e7256a4f575e)

**Additional information (please complete the following information):**
 > Transformation Pack Version : 3.5.4
 > Language Pack Version : 3.5.4

**Comment by aliasmaychange** [comment]
This is not the only string that has to be fixed, by the way.

**Comment by aliasmaychange** [comment]
@iongsd better see this.

**Comment by iongsd** [comment]
I've done the necessary changes. You can go ahead and close this issue.

> @iongsd better see this.
