### ISSUE TITLE
Unplugging laptop causes the DWM to crash

### ISSUE THREAD

**Issue by 404Dev-404** [ImSwordQueen/Win10to7Issues#88]
**Describe the bug**
> When I unplug my charger from the laptop (HP EliteBook G6) the desktop manager crashes (screen goes black for a second and the windows pop back up.)

**To Reproduce**
> Remove the charger from the laptop

**Screenshots**
> I can't take screenshots if the desktop manager isn't running.

**Additional information (please complete the following information):**
 > OS Version  : Windows 10 22H2
 > Transformation Pack Version : 3.5.4

**Additional context**
This did not happen before the transformation was installed

**Comment by 404Dev-404** [comment]
nevermind i'm uninstalling the transformation

**Comment by aliasmaychange** [comment]
Another guy who has an HP, decided to test this out, and I managed to kinda reproduce it, though the caveat is that it comes back immediately on my end.

**Comment by aliasmaychange** [comment]
May be an OpenGlass issue if anything.
