### ISSUE TITLE
A way to have both Task Manager versions accessible without doing the full reinstall/restart?

### ISSUE THREAD

**Issue by Joe-Applebrook** [ImSwordQueen/Win10to7Issues#89]
H! I’m really loving the transformation pack, and while I like the look of the old task manager, sometimes I need the windows 10 one because it’s just got a lot of features I use like the ability to see what percent of my CPU/GPU is being used by a process. I was just wondering if it would be possible to either have both versions installed at once (with one maybe being treated as just a regular program and one being like the main one that windows uses). If not, maybe a way to switch between the two without reinstalling/rebooting?
Thank you so much in advance! You’ve done an amazing job on this pack!

**Comment by micro2547** [comment]
this is literally exactly what i need wtf

**Comment by ImSwordQueen** [comment]
Sadly, the way that the old taskmgr installer does it is that it redirects the taskmgr via the registry. you could copy the new one in a separate place with a different name (Keeping both the executable and MUi in a folder named system32 and the MUN file in a folder named SystemResources) or uninstall the old one with the uninstaller in C:\Program Files\ClassicTaskmgr

**Comment by Joe-Applebrook** [comment]
> Sadly, the way that the old taskmgr installer does it is that it redirects the taskmgr via the registry. you could copy the new one in a separate place with a different name (Keeping both the executable and MUi in a folder named system32 and the MUN file in a folder named SystemResources) or uninstall the old one with the uninstaller in C:\Program Files\ClassicTaskmgr

That works. Thank you!
