### ISSUE TITLE
Some icons not removed after uninstallation

### ISSUE THREAD

**Issue by IsaacGibsound** [ImSwordQueen/Win10to7Issues#91]
**Describe the bug**
> A clear and concise description of what the bug is:

After uninstalling the program via Windows Settings > Apps > Apps & Features (which ran your uninstaller), there are some icons (including my File Explorer and Control Panel icons in the taskbar) which are left looking the way your transformation pack made them look. While fixing this bug is probably a good idea, what I primarily desire at the moment is simply to get my icons back to looking the way they did in stock Windows 10. So, if you could tell me how I can accomplish that, I would appreciate it! :)

**To Reproduce**
> Steps to reproduce the behavior:

Install the transformation pack using "Install Transformation Pack.exe" (found in the root directory of the Mega link from [DeviantArt](https://www.deviantart.com/imswordqueeen/art/Windows-10-21H2-22H2-to-7-Transformation-Pack-1081353677)). Then, uninstall the program via Windows Settings > Apps > Apps & Features. (Uninstalling by simply directly opening the aforementioned "Install Transformation Pack.exe" probably does the same thing, but I have not tested it.)

**Screenshots**
> If applicable, add screenshots to help explain your problem:
![File Manager and Control Panel in Taskbar](https://github.com/user-attachments/assets/7222e2c1-7326-42e6-9ec6-8eba651c7cd0)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 Pro 2023 22H2 19045.4957
 > Transformation Pack Version : 3.5.4

**Additional context**
I did try rebooting, but this did not solve the problem.

**Comment by IsaacGibsound** [comment]
Update: After going to sleep and getting back up, this bug seems to have solved itself—my icons are now back to the normal stock Windows 10 icons, at least those two icons that I mentioned earlier (and I have not noticed any icons that are not back to normal now). So, nothing probably needs to be done, unless you want to find a way for the stock Windows 10 icons to be restored the instant that uninstallation is finished. I am going to close this issue.

**Comment by ImSwordQueen** [comment]
To fix this issue you could just clear the icon cache and the icons would return to the windows 10 ones if it ever happens again.
