### ISSUE TITLE
Windhawk's problem.

### ISSUE THREAD

**Issue by YusufDanish** [ImSwordQueen/Win10to7Issues#92]
**Describe the bug**
> For some reason whenever I reinstall Windhawk 1.5.1, Some applications won't open except for the Microsoft applications and everything here was somehow broken, It won't be broken if windhawk was closed by restarting.:

Description ....

**To Reproduce**
> Steps to reproduce the behavior:

Description ....

**Screenshots**
> If applicable, add screenshots to help explain your problem:

**Additional information (please complete the following information):**
 > OS Version : [e.g. Windows 10 22H2]
 > Transformation Pack Version : [e.g. 3.5.3 to 3.5.4]

**Additional context**

**Comment by ImSwordQueen** [comment]
what do you mean by broken? do you have anything to visualize so i can see what you mean by that?

**Comment by YusufDanish** [comment]
> what do you mean by broken? do you have anything to visualize so i can see what you mean by that?

Here is an example: When I tried to open Bejeweled 2, It didn't show up, So that's why I need this to get fixed, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.

**Comment by ImSwordQueen** [comment]
> > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> 
> Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.

I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.

**Comment by YusufDanish** [comment]
> > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > 
> > 
> > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> 
> I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.

Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) update?

**Comment by ImSwordQueen** [comment]
> > > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > > 
> > > 
> > > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> > 
> > 
> > I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.
> 
> Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) from the old ones?

I generally don't offer old versions past 1 release as i don't offer support for those versions.

For the other issue, have you tried reinstalling the transformation pack from a clean state?

**Comment by YusufDanish** [comment]
> > > > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > > > 
> > > > 
> > > > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> > > 
> > > 
> > > I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.
> > 
> > 
> > Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) from the old ones?
> 
> I generally don't offer old versions past 1 release as i don't offer support for those versions.
> 
> For the other issue, have you tried reinstalling the transformation pack from a clean state?

No, Unfortunately I don't know how to do that.

**Comment by ImSwordQueen** [comment]
> > > > > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > > > > 
> > > > > 
> > > > > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> > > > 
> > > > 
> > > > I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.
> > > 
> > > 
> > > Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) from the old ones?
> > 
> > 
> > I generally don't offer old versions past 1 release as i don't offer support for those versions.
> > For the other issue, have you tried reinstalling the transformation pack from a clean state?
> 
> No, Unfortunately I don't know how to do that.

![image](https://github.com/user-attachments/assets/a3e8476c-96d2-4a7f-8438-2afdd50e003e)
![image](https://github.com/user-attachments/assets/1cccd902-84b1-4922-a972-4c3356169ba1)

**Comment by YusufDanish** [comment]
> > > > > > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > > > > > 
> > > > > > 
> > > > > > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> > > > > 
> > > > > 
> > > > > I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.
> > > > 
> > > > 
> > > > Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) from the old ones?
> > > 
> > > 
> > > I generally don't offer old versions past 1 release as i don't offer support for those versions.
> > > For the other issue, have you tried reinstalling the transformation pack from a clean state?
> > 
> > 
> > No, Unfortunately I don't know how to do that.
> 
> ![image](https://private-user-images.githubusercontent.com/52015098/375421467-a3e8476c-96d2-4a7f-8438-2afdd50e003e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDc5MjIsIm5iZiI6MTcyODYwNzYyMiwicGF0aCI6Ii81MjAxNTA5OC8zNzU0MjE0NjctYTNlODQ3NmMtOTZkMi00YTdmLTg0MzgtMmFmZGQ1MGUwMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAwNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGFlOTRmZGYxZDQ2MzkxMDliZDI3Y2MwNmE1MTA0MjM3MDY5NWY3MDBmODY0ZjhlZjRjYzcyN2MyMjcyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JkS4my9GybEMboybYJ9mKFf58FE-ulwuTRGgjKgGaBA) ![image](https://private-user-images.githubusercontent.com/52015098/375421577-1cccd902-84b1-4922-a972-4c3356169ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDc5MjIsIm5iZiI6MTcyODYwNzYyMiwicGF0aCI6Ii81MjAxNTA5OC8zNzU0MjE1NzctMWNjY2Q5MDItODRiMS00OTIyLWE5NzItNGMzMzU2MTY5YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAwNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOTQxODQ2M2M3Yzk1NTFjYWQ5ZTRmZTAzYzY5YTZjNTIxMjY1NTk2NWQwYWRiNWIxNzY3MTdjMTMxMGE5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9FX3NM3otG9NqsMnKuom1tOnvqgBR5ldj_cwaSy-LyU)

I forgot to say this but, Whenever I tried going to a "Personalization" on context, It did not do anything, But when I tried going to that by using a control panel, It just freeze for no reason at all.

**Comment by ImSwordQueen** [comment]
> > > > > > > > what do you mean by broken? do you have anything to visualize so i can see what you mean by that?
> > > > > > > 
> > > > > > > 
> > > > > > > Here is an example: When I tried to open Bejeweled 2 and other games, It didn't show up, Microsoft Games only showed up, Also sometimes the screen gets freaked out as some Windhawk mods were failed to initializing.
> > > > > > 
> > > > > > 
> > > > > > I tried Bejeweled 2 deluxe and it runs fine on my end. Also strange how some mods failed for you.
> > > > > 
> > > > > 
> > > > > Yeah it does that sometimes, The screen also got a black screen so I had to force shutdown so that Windhawk can be closed, Do you think you can try and add Fly High (3.5.2) from the old ones?
> > > > 
> > > > 
> > > > I generally don't offer old versions past 1 release as i don't offer support for those versions.
> > > > For the other issue, have you tried reinstalling the transformation pack from a clean state?
> > > 
> > > 
> > > No, Unfortunately I don't know how to do that.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/52015098/375421467-a3e8476c-96d2-4a7f-8438-2afdd50e003e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDc5MjIsIm5iZiI6MTcyODYwNzYyMiwicGF0aCI6Ii81MjAxNTA5OC8zNzU0MjE0NjctYTNlODQ3NmMtOTZkMi00YTdmLTg0MzgtMmFmZGQ1MGUwMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAwNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGFlOTRmZGYxZDQ2MzkxMDliZDI3Y2MwNmE1MTA0MjM3MDY5NWY3MDBmODY0ZjhlZjRjYzcyN2MyMjcyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JkS4my9GybEMboybYJ9mKFf58FE-ulwuTRGgjKgGaBA) ![image](https://private-user-images.githubusercontent.com/52015098/375421577-1cccd902-84b1-4922-a972-4c3356169ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDc5MjIsIm5iZiI6MTcyODYwNzYyMiwicGF0aCI6Ii81MjAxNTA5OC8zNzU0MjE1NzctMWNjY2Q5MDItODRiMS00OTIyLWE5NzItNGMzMzU2MTY5YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAwNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOTQxODQ2M2M3Yzk1NTFjYWQ5ZTRmZTAzYzY5YTZjNTIxMjY1NTk2NWQwYWRiNWIxNzY3MTdjMTMxMGE5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9FX3NM3otG9NqsMnKuom1tOnvqgBR5ldj_cwaSy-LyU)
> 
> I forgot to say this but, Whenever I tried going to a "Personalization" on context, It did not do anything, But when I tried going to that by using a control panel, It just freeze for no reason at all.

okay if so that happens then you can go to C:\Windows\Win10to7\SetupTools and run setup.exe and uninstall the pack that way

**Comment by ImSwordQueen** [comment]
I think this issue has been resolved or no longer an issue. I'm gonna close it for now.
