### ISSUE TITLE
Theme colour constantly different shades of red no matter which one is picked

### ISSUE THREAD

**Issue by 404Dev-404** [ImSwordQueen/Win10to7Issues#93]
**Describe the bug**
In the Personalization menu in the Control Panel, no matter what colour I select, it turns into a random shade of the colour red.

**To Reproduce**
Right click on the Desktop, click Personalize, go into Window Color, and pick any colour.

**Screenshots**
![Screenshot 2024-10-18 200851](https://github.com/user-attachments/assets/92278d68-9d61-4a09-b67b-318c0c10d844)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2
 > Transformation Pack Version : 3.5.4

**Additional context**
Unlike my previous issue, this is not on my laptop, but on my desktop PC (Dell Optiplex 790).

**Comment by ImSwordQueen** [comment]
I think OpenGlass symbols didn't download properly. Try copying the symbols folder from c:\awm into c:\windows\openglass and restart OpenGlass via task scheduler.

**Comment by 404Dev-404** [comment]
It's fixed now, thanks!
