### ISSUE TITLE
Using OpenShell instead of StartIsBack

### ISSUE THREAD

**Issue by Respite09** [ImSwordQueen/Win10to7Issues#94]
### Ask your question here

Can I uninstall StartIsBack myself and then use OpenShell instead? Or does it need StartIsBack for the taskbar?

**Comment by ImSwordQueen** [comment]
StartIsBack is needed for the taskbar. The closest thing to the Windows 7's taskbar is explorer7 (which is in early beta) or EP_Taskbar (Same thing)

**Comment by Respite09** [comment]
> StartIsBack is needed for the taskbar. The closest thing to the Windows 7's taskbar is explorer7 (which is in early beta) or EP_Taskbar (Same thing)

Ah ok, thank you!
