### ISSUE TITLE
Installation hangs at Stage 2 of 4

### ISSUE THREAD

**Issue by p950jgs5a** [ImSwordQueen/Win10to7Issues#96]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 LTSC 2021 21H2

### What version of the Transformation Pack are you having issues with?

3.5.4

### Summarise the issue

I previously installed & uninstalled the software perfectly. As I try to reinstall it, the installer stops at stage 2 of 4. The PC never restarts to finish the installation. The screen just turns black as explorer is shut down, but ctrl+alt+del & the Task Manager remain functional for me to easily restart Explorer.

I tried deleting the registry key  "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Win10to7" & clearing the Win10to7 folder from c:\windows, but it doesn't help. Windhawk & StartisBack++ get installed alongside 'Windows 7 Games', but nothing else as the installation never completes.

*I selected the default options during the installation process.

### How do you reproduce the bug/inaccuracy?

1. Install
2. Uninstall
3. Try to Reinstall

### Expected behaviour

The Installation process doesn't complete.

**Comment by ImSwordQueen** [comment]
I think this bug is caused by a weird configuration of windows (Unless defender removed the second phase setup which can happen and it sucks). If you are sure that setup.exe is still in the Win10to7 folder in setuptools.... go in regedit, `HKEY_LOCAL_MACHINE\SYSTEM\Setup` and copy:

CmdLine - C:\Windows\Win10to7\SetupTools\setup.exe

SetupPhase - 4

SetupType - 2

SystemSetupInProgress - 1

You should copy these as indicasted as a wrong value could cause windows to not boot anymore.

**Comment by p950jgs5a** [comment]
> I think this bug is caused by a weird configuration of windows (Unless defender removed the second phase setup which can happen and it sucks). If you are sure that setup.exe is still in the Win10to7 folder in setuptools.... go in regedit, `HKEY_LOCAL_MACHINE\SYSTEM\Setup` and copy:
> 
> CmdLine - C:\Windows\Win10to7\SetupTools\setup.exe
> 
> SetupPhase - 4
> 
> SetupType - 2
> 
> SystemSetupInProgress - 1
> 
> You should copy these as indicasted as a wrong value could cause windows to not boot anymore.

The Setup values are all 0, the installer doesn't even get to that point. The Windows Application Logs show Event ID 1033 & Error Status 1603 when the DVD Player & Media Center MSIs try to install.

**Comment by ImSwordQueen** [comment]
> > I think this bug is caused by a weird configuration of windows (Unless defender removed the second phase setup which can happen and it sucks). If you are sure that setup.exe is still in the Win10to7 folder in setuptools.... go in regedit, `HKEY_LOCAL_MACHINE\SYSTEM\Setup` and copy:
> > CmdLine - C:\Windows\Win10to7\SetupTools\setup.exe
> > SetupPhase - 4
> > SetupType - 2
> > SystemSetupInProgress - 1
> > You should copy these as indicasted as a wrong value could cause windows to not boot anymore.
> 
> The Setup values are all 0, the installer doesn't even get to that point. The Windows Application Logs show Event ID 1033 & Error Status 1603 when the DVD Player & Media Center MSIs try to install.

Hm. Okay... For now you can disable media center installer and install it manually thru this: https://garyan2.github.io/win10.html for now.

I will troubleshoot why this happens.

**Comment by p950jgs5a** [comment]
> > > I think this bug is caused by a weird configuration of windows (Unless defender removed the second phase setup which can happen and it sucks). If you are sure that setup.exe is still in the Win10to7 folder in setuptools.... go in regedit, `HKEY_LOCAL_MACHINE\SYSTEM\Setup` and copy:
> > > CmdLine - C:\Windows\Win10to7\SetupTools\setup.exe
> > > SetupPhase - 4
> > > SetupType - 2
> > > SystemSetupInProgress - 1
> > > You should copy these as indicasted as a wrong value could cause windows to not boot anymore.
> > 
> > 
> > The Setup values are all 0, the installer doesn't even get to that point. The Windows Application Logs show Event ID 1033 & Error Status 1603 when the DVD Player & Media Center MSIs try to install.
> 
> Hm. Okay... For now you can disable media center installer and install it manually thru this: https://garyan2.github.io/win10.html for now.
> 
> I will troubleshoot why this happens.

When I uncheck Media Center the installation halts at MSI 'C5E3A69D-D393-45A6-A8FB-00B01E2B010D'. I installed Visual Studio 2022 between the original uninstall (when it was working fine) & the original reinstall.

**Comment by ImSwordQueen** [comment]
That is vcredist 2022 failing to install.... Could you try reinstall vc redist 2022 thru the MS site and retry?

**Comment by ImSwordQueen** [comment]
but at a closer inspection... msiexec seems to be failing to install all msi packages and not only vcredist...

**Comment by p950jgs5a** [comment]
The latest VC++ 2022 Minimum Runtime minimum runtime is 14.40.33816 from the Microsoft site, it installs fine. The 10 to 7 pack uninstalls 14.40.33816 & installs 14.40.33810, also successfully. After that event the 10 to 7 pack MSIs fail to install.

**Comment by ImSwordQueen** [comment]
Does it only fail or does it halt the install completely?

**Comment by p950jgs5a** [comment]
> Does it only fail or does it halt the install completely?

It still halts at stage 2 of 4, even after the sfc /scannow

**Comment by ImSwordQueen** [comment]
I would try uninstalling vcredist 2022 and retry. I should find a way to make the installer not halt there.

**Comment by p950jgs5a** [comment]
> I would try uninstalling vcredist 2022 and retry. I should find a way to make the installer not halt there.

It appears to be built into Visual Studio 2022 as part of the 'C++ 2022 Redistributable Update'.

**Comment by ImSwordQueen** [comment]
> > I would try uninstalling vcredist 2022 and retry. I should find a way to make the installer not halt there.
> 
> It appears to be built into Visual Studio 2022 as part of the 'C++ 2022 Redistributable Update'.

Okay i tried replicating the issue and i don't seem to be able to replicate it. Can you try installing a normal MSI package that isn't from 21H2to7 and see if those work?

**Comment by p950jgs5a** [comment]
> Also to temp solve the issue if the MSI install issue isn't an install wide issue is to keep task manager open with always on top and when it goes to second phase and it gets stuck you should minimize the main installer window and see if any errors appear (please screenshot them if they do)

I uninstalled & reinstalled the 7zip msi, it works fine. There isn't anything to screenshot as the screen simply goes to black with explorer terminated after 'stage 2 of 4' completes. Ctrl+Alt+Del with the Task Manager can bring it back. The installation still halts at the  'C5E3A69D-D393-45A6-A8FB-00B01E2B010D' msi.

**Comment by ImSwordQueen** [comment]
Okay. I will compile a version of 21H2to7 with a check that doesn't install VCredist and see if that one works

**Comment by p950jgs5a** [comment]
> Okay. I will compile a version of 21H2to7 with a check that doesn't install VCredist and see if that one works

You can just try to install an MSI from the pack like the DVD Player while Visual Studio 2022 is installed. You can see the problem like that.

**Comment by ImSwordQueen** [comment]
Could you try this build? https://mega.nz/file/RyRFjI4A#PqQVbnGWxvcwYkQfaGAYlxkGY2jCx0wuhOJYwMz-QjQ

**Comment by p950jgs5a** [comment]
The DVD Player MSI is signed by Microsoft. The problem appears to be a Visual Studio 2022 compatibility issue. The version of vc++ 2015-2022 included in it conflicts with the MSIs in the pack.

**Comment by ImSwordQueen** [comment]
> The DVD Player MSI is signed by Microsoft. The problem appears to be a Visual Studio 2022 compatibility issue. The version of vc++ 2015-2022 included in it conflicts with the MSIs in the pack.

So does using the version i compiled works now?

**Comment by p950jgs5a** [comment]
> > The DVD Player MSI is signed by Microsoft. The problem appears to be a Visual Studio 2022 compatibility issue. The version of vc++ 2015-2022 included in it conflicts with the MSIs in the pack.
> 
> So does the version i compiled works now?

No, the individual MSIs from the pack are not installing.

**Comment by ImSwordQueen** [comment]
I tried every configuration and it doesn't seem to hang on my end. Even with VS 2022 installed with the vcredist.

**Comment by p950jgs5a** [comment]
I looked at the msi logs & noticed that powershell had somehow been removed from the system path. I added it back & it's installing/uninstalling again.
