### ISSUE TITLE
Explorer ribbon is not affected by dark theme

### ISSUE THREAD

**Issue by ApianCat** [ImSwordQueen/Win10to7Issues#97]
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

22H2

### What version of the Transformation Pack are you having issues with?

3.5.4

### Summarise the issue

The ribbon of Windows Explorer doesn't work when selecting the included Windows 7 (Dark) theme

### Screenshots

![image](https://github.com/user-attachments/assets/4564bf3c-aa62-4626-9a09-9e00590ee930)

### How do you reproduce the bug/inaccuracy?

1. Select the Windows 7 (Dark) theme from Control Panel or Settings
2. Open Windows Explorer

### Expected behaviour

The ribbon should be dark like the rest of Windows Explorer

**Comment by ImSwordQueen** [comment]
Sadly this is a limitation with the old ribbon(s). The switch that makes the ribbon dark was only implemented in 1809 and it is currently impossible to replicate the old ribbon on the newer ribbon.
