### ISSUE TITLE
winaero support, general install support

### ISSUE THREAD

**Issue by MemLiveOn** [ImSwordQueen/Win10to7Issues#99]
### Ask your question here

I want to make sure that winaero tweaker doesn't get broken or if I can just reinstall winaero and get a few more tweaks there.
Also I want to make sure I can install this on my main computer without breaking anything. There is nothing telling me if this is supposed to be installed on a fresh iso or if anything installed _before_ the transformation may get messed up. If it can, I suggest adding that to the faq just for the simple sake of a warning. Note, I have not tried it yet, but got it from a endermanch video and do want to try it, but don't want to risk breaking anything.

I give [Endermanch](https://youtu.be/kYVlULPFHsM) full credit for bringing me to your program.

**Comment by ImSwordQueen** [comment]
Winaero tweaker doesn't break with 21H2to7. Only one downside is that winaero hardcodes some colors to white so the dark mode theme would have unreadable text with it.
